#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TWO")]
public partial class AlereVerbalAuthExistingPatientDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAS_Alere_VAEP_Record(AS_Alere_VAEP_Record instance);
  partial void UpdateAS_Alere_VAEP_Record(AS_Alere_VAEP_Record instance);
  partial void DeleteAS_Alere_VAEP_Record(AS_Alere_VAEP_Record instance);
  partial void InsertAS_Alere_VAEP_CB(AS_Alere_VAEP_CB instance);
  partial void UpdateAS_Alere_VAEP_CB(AS_Alere_VAEP_CB instance);
  partial void DeleteAS_Alere_VAEP_CB(AS_Alere_VAEP_CB instance);
  partial void InsertAS_Alere_VAEP_PickList(AS_Alere_VAEP_PickList instance);
  partial void UpdateAS_Alere_VAEP_PickList(AS_Alere_VAEP_PickList instance);
  partial void DeleteAS_Alere_VAEP_PickList(AS_Alere_VAEP_PickList instance);
  partial void InsertAS_Alere_VAEP_Records_AuditTrail(AS_Alere_VAEP_Records_AuditTrail instance);
  partial void UpdateAS_Alere_VAEP_Records_AuditTrail(AS_Alere_VAEP_Records_AuditTrail instance);
  partial void DeleteAS_Alere_VAEP_Records_AuditTrail(AS_Alere_VAEP_Records_AuditTrail instance);
  partial void InsertAS_Alere_VAEP_Detail(AS_Alere_VAEP_Detail instance);
  partial void UpdateAS_Alere_VAEP_Detail(AS_Alere_VAEP_Detail instance);
  partial void DeleteAS_Alere_VAEP_Detail(AS_Alere_VAEP_Detail instance);
  #endregion
	
	public AlereVerbalAuthExistingPatientDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TWOConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public AlereVerbalAuthExistingPatientDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlereVerbalAuthExistingPatientDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlereVerbalAuthExistingPatientDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlereVerbalAuthExistingPatientDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AS_Alere_VAEP_Record> AS_Alere_VAEP_Records
	{
		get
		{
			return this.GetTable<AS_Alere_VAEP_Record>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_VAEP_CB> AS_Alere_VAEP_CBs
	{
		get
		{
			return this.GetTable<AS_Alere_VAEP_CB>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_VAEP_PickList> AS_Alere_VAEP_PickLists
	{
		get
		{
			return this.GetTable<AS_Alere_VAEP_PickList>();
		}
	}
	
	public System.Data.Linq.Table<uvw_AHM_Patient_Detail> uvw_AHM_Patient_Details
	{
		get
		{
			return this.GetTable<uvw_AHM_Patient_Detail>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_VAEP_Records_AuditTrail> AS_Alere_VAEP_Records_AuditTrails
	{
		get
		{
			return this.GetTable<AS_Alere_VAEP_Records_AuditTrail>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_VAEP_Detail> AS_Alere_VAEP_Details
	{
		get
		{
			return this.GetTable<AS_Alere_VAEP_Detail>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_VAEP_Records")]
public partial class AS_Alere_VAEP_Record : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _RecordID;
	
	private string _PatientID;
	
	private string _CreatedBy;
	
	private string _WorkflowState;
	
	private string _NoteColumn;
	
	private string _DetailApproverNoteColumn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(string value);
    partial void OnRecordIDChanged();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnWorkflowStateChanging(string value);
    partial void OnWorkflowStateChanged();
    partial void OnNoteColumnChanging(string value);
    partial void OnNoteColumnChanged();
    partial void OnDetailApproverNoteColumnChanging(string value);
    partial void OnDetailApproverNoteColumnChanged();
    #endregion
	
	public AS_Alere_VAEP_Record()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string RecordID
	{
		get
		{
			return this._RecordID;
		}
		set
		{
			if ((this._RecordID != value))
			{
				this.OnRecordIDChanging(value);
				this.SendPropertyChanging();
				this._RecordID = value;
				this.SendPropertyChanged("RecordID");
				this.OnRecordIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15)")]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(250)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowState", DbType="NVarChar(250)")]
	public string WorkflowState
	{
		get
		{
			return this._WorkflowState;
		}
		set
		{
			if ((this._WorkflowState != value))
			{
				this.OnWorkflowStateChanging(value);
				this.SendPropertyChanging();
				this._WorkflowState = value;
				this.SendPropertyChanged("WorkflowState");
				this.OnWorkflowStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteColumn", DbType="NVarChar(250)")]
	public string NoteColumn
	{
		get
		{
			return this._NoteColumn;
		}
		set
		{
			if ((this._NoteColumn != value))
			{
				this.OnNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._NoteColumn = value;
				this.SendPropertyChanged("NoteColumn");
				this.OnNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailApproverNoteColumn", DbType="NVarChar(250)")]
	public string DetailApproverNoteColumn
	{
		get
		{
			return this._DetailApproverNoteColumn;
		}
		set
		{
			if ((this._DetailApproverNoteColumn != value))
			{
				this.OnDetailApproverNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._DetailApproverNoteColumn = value;
				this.SendPropertyChanged("DetailApproverNoteColumn");
				this.OnDetailApproverNoteColumnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_VAEP_CBs")]
public partial class AS_Alere_VAEP_CB : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _RecordID;
	
	private System.Nullable<bool> _Gender;
	
	private System.Nullable<bool> _PrimaryPhone;
	
	private System.Nullable<bool> _SecondaryPhone;
	
	private System.Nullable<bool> _Email;
	
	private System.Nullable<bool> _Caregiver;
	
	private System.Nullable<bool> _CaregiverRelationship;
	
	private System.Nullable<bool> _CaregiverPrimaryPhone;
	
	private System.Nullable<bool> _CaregiverSecondaryPhone;
	
	private System.Nullable<bool> _CaregiverPOA;
	
	private System.Nullable<bool> _Physician;
	
	private System.Nullable<bool> _PhysicianFax;
	
	private System.Nullable<bool> _PhysicianPhone;
	
	private System.Nullable<bool> _ReportResultsTo;
	
	private System.Nullable<bool> _ReportResultsToPhone;
	
	private System.Nullable<bool> _ReportResultsToFax;
	
	private System.Nullable<bool> _AfterHoursInstruction;
	
	private System.Nullable<bool> _Clinic;
	
	private System.Nullable<bool> _ClinicAddress;
	
	private System.Nullable<bool> _ClinicCityStateZip;
	
	private System.Nullable<bool> _ClinicPhone;
	
	private System.Nullable<bool> _MeterType;
	
	private System.Nullable<bool> _TestFrequency;
	
	private System.Nullable<bool> _APLSDiscussion;
	
	private System.Nullable<bool> _TestReportingInstruction;
	
	private System.Nullable<bool> _FaxAllResults;
	
	private System.Nullable<bool> _MBE;
	
	private System.Nullable<bool> _MBEDate;
	
	private System.Nullable<bool> _SelectOptions;
	
	private System.Nullable<bool> _RetestIn;
	
	private System.Nullable<bool> _OtherOptions;
	
	private System.Nullable<bool> _AuthorizedBy;
	
	private System.Nullable<bool> _AuthorizedByTitle;
	
	private System.Nullable<bool> _TakenBy;
	
	private System.Nullable<bool> _TakenByTitle;
	
	private System.Nullable<bool> _Date;
	
	private System.Nullable<bool> _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(string value);
    partial void OnRecordIDChanged();
    partial void OnGenderChanging(System.Nullable<bool> value);
    partial void OnGenderChanged();
    partial void OnPrimaryPhoneChanging(System.Nullable<bool> value);
    partial void OnPrimaryPhoneChanged();
    partial void OnSecondaryPhoneChanging(System.Nullable<bool> value);
    partial void OnSecondaryPhoneChanged();
    partial void OnEmailChanging(System.Nullable<bool> value);
    partial void OnEmailChanged();
    partial void OnCaregiverChanging(System.Nullable<bool> value);
    partial void OnCaregiverChanged();
    partial void OnCaregiverRelationshipChanging(System.Nullable<bool> value);
    partial void OnCaregiverRelationshipChanged();
    partial void OnCaregiverPrimaryPhoneChanging(System.Nullable<bool> value);
    partial void OnCaregiverPrimaryPhoneChanged();
    partial void OnCaregiverSecondaryPhoneChanging(System.Nullable<bool> value);
    partial void OnCaregiverSecondaryPhoneChanged();
    partial void OnCaregiverPOAChanging(System.Nullable<bool> value);
    partial void OnCaregiverPOAChanged();
    partial void OnPhysicianChanging(System.Nullable<bool> value);
    partial void OnPhysicianChanged();
    partial void OnPhysicianFaxChanging(System.Nullable<bool> value);
    partial void OnPhysicianFaxChanged();
    partial void OnPhysicianPhoneChanging(System.Nullable<bool> value);
    partial void OnPhysicianPhoneChanged();
    partial void OnReportResultsToChanging(System.Nullable<bool> value);
    partial void OnReportResultsToChanged();
    partial void OnReportResultsToPhoneChanging(System.Nullable<bool> value);
    partial void OnReportResultsToPhoneChanged();
    partial void OnReportResultsToFaxChanging(System.Nullable<bool> value);
    partial void OnReportResultsToFaxChanged();
    partial void OnAfterHoursInstructionChanging(System.Nullable<bool> value);
    partial void OnAfterHoursInstructionChanged();
    partial void OnClinicChanging(System.Nullable<bool> value);
    partial void OnClinicChanged();
    partial void OnClinicAddressChanging(System.Nullable<bool> value);
    partial void OnClinicAddressChanged();
    partial void OnClinicCityStateZipChanging(System.Nullable<bool> value);
    partial void OnClinicCityStateZipChanged();
    partial void OnClinicPhoneChanging(System.Nullable<bool> value);
    partial void OnClinicPhoneChanged();
    partial void OnMeterTypeChanging(System.Nullable<bool> value);
    partial void OnMeterTypeChanged();
    partial void OnTestFrequencyChanging(System.Nullable<bool> value);
    partial void OnTestFrequencyChanged();
    partial void OnAPLSDiscussionChanging(System.Nullable<bool> value);
    partial void OnAPLSDiscussionChanged();
    partial void OnTestReportingInstructionChanging(System.Nullable<bool> value);
    partial void OnTestReportingInstructionChanged();
    partial void OnFaxAllResultsChanging(System.Nullable<bool> value);
    partial void OnFaxAllResultsChanged();
    partial void OnMBEChanging(System.Nullable<bool> value);
    partial void OnMBEChanged();
    partial void OnMBEDateChanging(System.Nullable<bool> value);
    partial void OnMBEDateChanged();
    partial void OnSelectOptionsChanging(System.Nullable<bool> value);
    partial void OnSelectOptionsChanged();
    partial void OnRetestInChanging(System.Nullable<bool> value);
    partial void OnRetestInChanged();
    partial void OnOtherOptionsChanging(System.Nullable<bool> value);
    partial void OnOtherOptionsChanged();
    partial void OnAuthorizedByChanging(System.Nullable<bool> value);
    partial void OnAuthorizedByChanged();
    partial void OnAuthorizedByTitleChanging(System.Nullable<bool> value);
    partial void OnAuthorizedByTitleChanged();
    partial void OnTakenByChanging(System.Nullable<bool> value);
    partial void OnTakenByChanged();
    partial void OnTakenByTitleChanging(System.Nullable<bool> value);
    partial void OnTakenByTitleChanged();
    partial void OnDateChanging(System.Nullable<bool> value);
    partial void OnDateChanged();
    partial void OnTimeChanging(System.Nullable<bool> value);
    partial void OnTimeChanged();
    #endregion
	
	public AS_Alere_VAEP_CB()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string RecordID
	{
		get
		{
			return this._RecordID;
		}
		set
		{
			if ((this._RecordID != value))
			{
				this.OnRecordIDChanging(value);
				this.SendPropertyChanging();
				this._RecordID = value;
				this.SendPropertyChanged("RecordID");
				this.OnRecordIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
	public System.Nullable<bool> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPhone", DbType="Bit")]
	public System.Nullable<bool> PrimaryPhone
	{
		get
		{
			return this._PrimaryPhone;
		}
		set
		{
			if ((this._PrimaryPhone != value))
			{
				this.OnPrimaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._PrimaryPhone = value;
				this.SendPropertyChanged("PrimaryPhone");
				this.OnPrimaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPhone", DbType="Bit")]
	public System.Nullable<bool> SecondaryPhone
	{
		get
		{
			return this._SecondaryPhone;
		}
		set
		{
			if ((this._SecondaryPhone != value))
			{
				this.OnSecondaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._SecondaryPhone = value;
				this.SendPropertyChanged("SecondaryPhone");
				this.OnSecondaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Bit")]
	public System.Nullable<bool> Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caregiver", DbType="Bit")]
	public System.Nullable<bool> Caregiver
	{
		get
		{
			return this._Caregiver;
		}
		set
		{
			if ((this._Caregiver != value))
			{
				this.OnCaregiverChanging(value);
				this.SendPropertyChanging();
				this._Caregiver = value;
				this.SendPropertyChanged("Caregiver");
				this.OnCaregiverChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverRelationship", DbType="Bit")]
	public System.Nullable<bool> CaregiverRelationship
	{
		get
		{
			return this._CaregiverRelationship;
		}
		set
		{
			if ((this._CaregiverRelationship != value))
			{
				this.OnCaregiverRelationshipChanging(value);
				this.SendPropertyChanging();
				this._CaregiverRelationship = value;
				this.SendPropertyChanged("CaregiverRelationship");
				this.OnCaregiverRelationshipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverPrimaryPhone", DbType="Bit")]
	public System.Nullable<bool> CaregiverPrimaryPhone
	{
		get
		{
			return this._CaregiverPrimaryPhone;
		}
		set
		{
			if ((this._CaregiverPrimaryPhone != value))
			{
				this.OnCaregiverPrimaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._CaregiverPrimaryPhone = value;
				this.SendPropertyChanged("CaregiverPrimaryPhone");
				this.OnCaregiverPrimaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverSecondaryPhone", DbType="Bit")]
	public System.Nullable<bool> CaregiverSecondaryPhone
	{
		get
		{
			return this._CaregiverSecondaryPhone;
		}
		set
		{
			if ((this._CaregiverSecondaryPhone != value))
			{
				this.OnCaregiverSecondaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._CaregiverSecondaryPhone = value;
				this.SendPropertyChanged("CaregiverSecondaryPhone");
				this.OnCaregiverSecondaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverPOA", DbType="Bit")]
	public System.Nullable<bool> CaregiverPOA
	{
		get
		{
			return this._CaregiverPOA;
		}
		set
		{
			if ((this._CaregiverPOA != value))
			{
				this.OnCaregiverPOAChanging(value);
				this.SendPropertyChanging();
				this._CaregiverPOA = value;
				this.SendPropertyChanged("CaregiverPOA");
				this.OnCaregiverPOAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physician", DbType="Bit")]
	public System.Nullable<bool> Physician
	{
		get
		{
			return this._Physician;
		}
		set
		{
			if ((this._Physician != value))
			{
				this.OnPhysicianChanging(value);
				this.SendPropertyChanging();
				this._Physician = value;
				this.SendPropertyChanged("Physician");
				this.OnPhysicianChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicianFax", DbType="Bit")]
	public System.Nullable<bool> PhysicianFax
	{
		get
		{
			return this._PhysicianFax;
		}
		set
		{
			if ((this._PhysicianFax != value))
			{
				this.OnPhysicianFaxChanging(value);
				this.SendPropertyChanging();
				this._PhysicianFax = value;
				this.SendPropertyChanged("PhysicianFax");
				this.OnPhysicianFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicianPhone", DbType="Bit")]
	public System.Nullable<bool> PhysicianPhone
	{
		get
		{
			return this._PhysicianPhone;
		}
		set
		{
			if ((this._PhysicianPhone != value))
			{
				this.OnPhysicianPhoneChanging(value);
				this.SendPropertyChanging();
				this._PhysicianPhone = value;
				this.SendPropertyChanged("PhysicianPhone");
				this.OnPhysicianPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportResultsTo", DbType="Bit")]
	public System.Nullable<bool> ReportResultsTo
	{
		get
		{
			return this._ReportResultsTo;
		}
		set
		{
			if ((this._ReportResultsTo != value))
			{
				this.OnReportResultsToChanging(value);
				this.SendPropertyChanging();
				this._ReportResultsTo = value;
				this.SendPropertyChanged("ReportResultsTo");
				this.OnReportResultsToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportResultsToPhone", DbType="Bit")]
	public System.Nullable<bool> ReportResultsToPhone
	{
		get
		{
			return this._ReportResultsToPhone;
		}
		set
		{
			if ((this._ReportResultsToPhone != value))
			{
				this.OnReportResultsToPhoneChanging(value);
				this.SendPropertyChanging();
				this._ReportResultsToPhone = value;
				this.SendPropertyChanged("ReportResultsToPhone");
				this.OnReportResultsToPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportResultsToFax", DbType="Bit")]
	public System.Nullable<bool> ReportResultsToFax
	{
		get
		{
			return this._ReportResultsToFax;
		}
		set
		{
			if ((this._ReportResultsToFax != value))
			{
				this.OnReportResultsToFaxChanging(value);
				this.SendPropertyChanging();
				this._ReportResultsToFax = value;
				this.SendPropertyChanged("ReportResultsToFax");
				this.OnReportResultsToFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterHoursInstruction", DbType="Bit")]
	public System.Nullable<bool> AfterHoursInstruction
	{
		get
		{
			return this._AfterHoursInstruction;
		}
		set
		{
			if ((this._AfterHoursInstruction != value))
			{
				this.OnAfterHoursInstructionChanging(value);
				this.SendPropertyChanging();
				this._AfterHoursInstruction = value;
				this.SendPropertyChanged("AfterHoursInstruction");
				this.OnAfterHoursInstructionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clinic", DbType="Bit")]
	public System.Nullable<bool> Clinic
	{
		get
		{
			return this._Clinic;
		}
		set
		{
			if ((this._Clinic != value))
			{
				this.OnClinicChanging(value);
				this.SendPropertyChanging();
				this._Clinic = value;
				this.SendPropertyChanged("Clinic");
				this.OnClinicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicAddress", DbType="Bit")]
	public System.Nullable<bool> ClinicAddress
	{
		get
		{
			return this._ClinicAddress;
		}
		set
		{
			if ((this._ClinicAddress != value))
			{
				this.OnClinicAddressChanging(value);
				this.SendPropertyChanging();
				this._ClinicAddress = value;
				this.SendPropertyChanged("ClinicAddress");
				this.OnClinicAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicCityStateZip", DbType="Bit")]
	public System.Nullable<bool> ClinicCityStateZip
	{
		get
		{
			return this._ClinicCityStateZip;
		}
		set
		{
			if ((this._ClinicCityStateZip != value))
			{
				this.OnClinicCityStateZipChanging(value);
				this.SendPropertyChanging();
				this._ClinicCityStateZip = value;
				this.SendPropertyChanged("ClinicCityStateZip");
				this.OnClinicCityStateZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicPhone", DbType="Bit")]
	public System.Nullable<bool> ClinicPhone
	{
		get
		{
			return this._ClinicPhone;
		}
		set
		{
			if ((this._ClinicPhone != value))
			{
				this.OnClinicPhoneChanging(value);
				this.SendPropertyChanging();
				this._ClinicPhone = value;
				this.SendPropertyChanged("ClinicPhone");
				this.OnClinicPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterType", DbType="Bit")]
	public System.Nullable<bool> MeterType
	{
		get
		{
			return this._MeterType;
		}
		set
		{
			if ((this._MeterType != value))
			{
				this.OnMeterTypeChanging(value);
				this.SendPropertyChanging();
				this._MeterType = value;
				this.SendPropertyChanged("MeterType");
				this.OnMeterTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestFrequency", DbType="Bit")]
	public System.Nullable<bool> TestFrequency
	{
		get
		{
			return this._TestFrequency;
		}
		set
		{
			if ((this._TestFrequency != value))
			{
				this.OnTestFrequencyChanging(value);
				this.SendPropertyChanging();
				this._TestFrequency = value;
				this.SendPropertyChanged("TestFrequency");
				this.OnTestFrequencyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APLSDiscussion", DbType="Bit")]
	public System.Nullable<bool> APLSDiscussion
	{
		get
		{
			return this._APLSDiscussion;
		}
		set
		{
			if ((this._APLSDiscussion != value))
			{
				this.OnAPLSDiscussionChanging(value);
				this.SendPropertyChanging();
				this._APLSDiscussion = value;
				this.SendPropertyChanged("APLSDiscussion");
				this.OnAPLSDiscussionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestReportingInstruction", DbType="Bit")]
	public System.Nullable<bool> TestReportingInstruction
	{
		get
		{
			return this._TestReportingInstruction;
		}
		set
		{
			if ((this._TestReportingInstruction != value))
			{
				this.OnTestReportingInstructionChanging(value);
				this.SendPropertyChanging();
				this._TestReportingInstruction = value;
				this.SendPropertyChanged("TestReportingInstruction");
				this.OnTestReportingInstructionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxAllResults", DbType="Bit")]
	public System.Nullable<bool> FaxAllResults
	{
		get
		{
			return this._FaxAllResults;
		}
		set
		{
			if ((this._FaxAllResults != value))
			{
				this.OnFaxAllResultsChanging(value);
				this.SendPropertyChanging();
				this._FaxAllResults = value;
				this.SendPropertyChanged("FaxAllResults");
				this.OnFaxAllResultsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBE", DbType="Bit")]
	public System.Nullable<bool> MBE
	{
		get
		{
			return this._MBE;
		}
		set
		{
			if ((this._MBE != value))
			{
				this.OnMBEChanging(value);
				this.SendPropertyChanging();
				this._MBE = value;
				this.SendPropertyChanged("MBE");
				this.OnMBEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBEDate", DbType="Bit")]
	public System.Nullable<bool> MBEDate
	{
		get
		{
			return this._MBEDate;
		}
		set
		{
			if ((this._MBEDate != value))
			{
				this.OnMBEDateChanging(value);
				this.SendPropertyChanging();
				this._MBEDate = value;
				this.SendPropertyChanged("MBEDate");
				this.OnMBEDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectOptions", DbType="Bit")]
	public System.Nullable<bool> SelectOptions
	{
		get
		{
			return this._SelectOptions;
		}
		set
		{
			if ((this._SelectOptions != value))
			{
				this.OnSelectOptionsChanging(value);
				this.SendPropertyChanging();
				this._SelectOptions = value;
				this.SendPropertyChanged("SelectOptions");
				this.OnSelectOptionsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetestIn", DbType="Bit")]
	public System.Nullable<bool> RetestIn
	{
		get
		{
			return this._RetestIn;
		}
		set
		{
			if ((this._RetestIn != value))
			{
				this.OnRetestInChanging(value);
				this.SendPropertyChanging();
				this._RetestIn = value;
				this.SendPropertyChanged("RetestIn");
				this.OnRetestInChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherOptions", DbType="Bit")]
	public System.Nullable<bool> OtherOptions
	{
		get
		{
			return this._OtherOptions;
		}
		set
		{
			if ((this._OtherOptions != value))
			{
				this.OnOtherOptionsChanging(value);
				this.SendPropertyChanging();
				this._OtherOptions = value;
				this.SendPropertyChanged("OtherOptions");
				this.OnOtherOptionsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizedBy", DbType="Bit")]
	public System.Nullable<bool> AuthorizedBy
	{
		get
		{
			return this._AuthorizedBy;
		}
		set
		{
			if ((this._AuthorizedBy != value))
			{
				this.OnAuthorizedByChanging(value);
				this.SendPropertyChanging();
				this._AuthorizedBy = value;
				this.SendPropertyChanged("AuthorizedBy");
				this.OnAuthorizedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizedByTitle", DbType="Bit")]
	public System.Nullable<bool> AuthorizedByTitle
	{
		get
		{
			return this._AuthorizedByTitle;
		}
		set
		{
			if ((this._AuthorizedByTitle != value))
			{
				this.OnAuthorizedByTitleChanging(value);
				this.SendPropertyChanging();
				this._AuthorizedByTitle = value;
				this.SendPropertyChanged("AuthorizedByTitle");
				this.OnAuthorizedByTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakenBy", DbType="Bit")]
	public System.Nullable<bool> TakenBy
	{
		get
		{
			return this._TakenBy;
		}
		set
		{
			if ((this._TakenBy != value))
			{
				this.OnTakenByChanging(value);
				this.SendPropertyChanging();
				this._TakenBy = value;
				this.SendPropertyChanged("TakenBy");
				this.OnTakenByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakenByTitle", DbType="Bit")]
	public System.Nullable<bool> TakenByTitle
	{
		get
		{
			return this._TakenByTitle;
		}
		set
		{
			if ((this._TakenByTitle != value))
			{
				this.OnTakenByTitleChanging(value);
				this.SendPropertyChanging();
				this._TakenByTitle = value;
				this.SendPropertyChanged("TakenByTitle");
				this.OnTakenByTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Bit")]
	public System.Nullable<bool> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Bit")]
	public System.Nullable<bool> Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_VAEP_PickLists")]
public partial class AS_Alere_VAEP_PickList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PicklistKey;
	
	private string _PicklistItem;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPicklistKeyChanging(string value);
    partial void OnPicklistKeyChanged();
    partial void OnPicklistItemChanging(string value);
    partial void OnPicklistItemChanged();
    #endregion
	
	public AS_Alere_VAEP_PickList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicklistKey", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PicklistKey
	{
		get
		{
			return this._PicklistKey;
		}
		set
		{
			if ((this._PicklistKey != value))
			{
				this.OnPicklistKeyChanging(value);
				this.SendPropertyChanging();
				this._PicklistKey = value;
				this.SendPropertyChanged("PicklistKey");
				this.OnPicklistKeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicklistItem", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PicklistItem
	{
		get
		{
			return this._PicklistItem;
		}
		set
		{
			if ((this._PicklistItem != value))
			{
				this.OnPicklistItemChanging(value);
				this.SendPropertyChanging();
				this._PicklistItem = value;
				this.SendPropertyChanged("PicklistItem");
				this.OnPicklistItemChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uvw_AHM_Patient_Detail")]
public partial class uvw_AHM_Patient_Detail
{
	
	private string _Patient_Number;
	
	private string _Patient_Last_Name;
	
	private string _Patient_First_Name;
	
	private System.DateTime _Birth_Date;
	
	private string _Patient_Address;
	
	private string _Patient_City;
	
	private string _Patient_State_Code;
	
	private string _Patient_ZipCode;
	
	private string _Phone_Number;
	
	private string _Email;
	
	private string _Meter_Type;
	
	private string _SA_Account_Number;
	
	private string _Referring_Source_Code;
	
	private string _Referring_Source_Name;
	
	private string _Primary_Physician_Name;
	
	private string _Primary_Physician_Phone_Number;
	
	private string _Primary_Physician_Address;
	
	private string _Primary_Physician_City;
	
	private string _Primary_Physician_State_Code;
	
	private string _Primary_Physician_ZipCode;
	
	private string _Primary_Plan_Name;
	
	private string _Primary_Policy_Number;
	
	private string _Primary_Group_Number;
	
	private string _Primary_Plan_Code;
	
	private string _Primary_Plan_Address;
	
	private string _Primary_Plan_State_Code;
	
	private string _Primary_Plan_ZipCode;
	
	private string _Primary_Plan_Phone;
	
	private System.Nullable<System.DateTime> _Primary_Plan_Effective_Date;
	
	private System.Nullable<System.DateTime> _Primary_Plan_Expiration_Date;
	
	private string _Secondary_Plan_Name;
	
	private string _Secondary_Policy_Number;
	
	private string _Secondary_Group_Number;
	
	private string _Secondary_Plan_Code;
	
	private string _Secondary_Plan_Address;
	
	private string _Secondary_Plan_State_Code;
	
	private string _Secondary_Plan_ZipCode;
	
	private string _Secondary_Plan_Phone;
	
	private System.Nullable<System.DateTime> _Secondary_Plan_Effective_Date;
	
	private System.Nullable<System.DateTime> _Secondary_Plan_Expiration_Date;
	
	private string _Primary_Plan_City;
	
	private string _Secondary_Plan_City;
	
	public uvw_AHM_Patient_Detail()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Number", DbType="Char(9) NOT NULL", CanBeNull=false)]
	public string Patient_Number
	{
		get
		{
			return this._Patient_Number;
		}
		set
		{
			if ((this._Patient_Number != value))
			{
				this._Patient_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Last_Name", DbType="Char(25) NOT NULL", CanBeNull=false)]
	public string Patient_Last_Name
	{
		get
		{
			return this._Patient_Last_Name;
		}
		set
		{
			if ((this._Patient_Last_Name != value))
			{
				this._Patient_Last_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_First_Name", DbType="Char(15) NOT NULL", CanBeNull=false)]
	public string Patient_First_Name
	{
		get
		{
			return this._Patient_First_Name;
		}
		set
		{
			if ((this._Patient_First_Name != value))
			{
				this._Patient_First_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birth_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Birth_Date
	{
		get
		{
			return this._Birth_Date;
		}
		set
		{
			if ((this._Birth_Date != value))
			{
				this._Birth_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Address", DbType="Char(31) NOT NULL", CanBeNull=false)]
	public string Patient_Address
	{
		get
		{
			return this._Patient_Address;
		}
		set
		{
			if ((this._Patient_Address != value))
			{
				this._Patient_Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_City", DbType="Char(25) NOT NULL", CanBeNull=false)]
	public string Patient_City
	{
		get
		{
			return this._Patient_City;
		}
		set
		{
			if ((this._Patient_City != value))
			{
				this._Patient_City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_State_Code", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string Patient_State_Code
	{
		get
		{
			return this._Patient_State_Code;
		}
		set
		{
			if ((this._Patient_State_Code != value))
			{
				this._Patient_State_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_ZipCode", DbType="Char(11) NOT NULL", CanBeNull=false)]
	public string Patient_ZipCode
	{
		get
		{
			return this._Patient_ZipCode;
		}
		set
		{
			if ((this._Patient_ZipCode != value))
			{
				this._Patient_ZipCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Number", DbType="VarChar(14)")]
	public string Phone_Number
	{
		get
		{
			return this._Phone_Number;
		}
		set
		{
			if ((this._Phone_Number != value))
			{
				this._Phone_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(61) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meter_Type", DbType="Char(7)")]
	public string Meter_Type
	{
		get
		{
			return this._Meter_Type;
		}
		set
		{
			if ((this._Meter_Type != value))
			{
				this._Meter_Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SA_Account_Number", DbType="Char(21)")]
	public string SA_Account_Number
	{
		get
		{
			return this._SA_Account_Number;
		}
		set
		{
			if ((this._SA_Account_Number != value))
			{
				this._SA_Account_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referring_Source_Code", DbType="Char(7) NOT NULL", CanBeNull=false)]
	public string Referring_Source_Code
	{
		get
		{
			return this._Referring_Source_Code;
		}
		set
		{
			if ((this._Referring_Source_Code != value))
			{
				this._Referring_Source_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referring_Source_Name", DbType="VarChar(50)")]
	public string Referring_Source_Name
	{
		get
		{
			return this._Referring_Source_Name;
		}
		set
		{
			if ((this._Referring_Source_Name != value))
			{
				this._Referring_Source_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Physician_Name", DbType="VarChar(50)")]
	public string Primary_Physician_Name
	{
		get
		{
			return this._Primary_Physician_Name;
		}
		set
		{
			if ((this._Primary_Physician_Name != value))
			{
				this._Primary_Physician_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Physician_Phone_Number", DbType="Char(11)")]
	public string Primary_Physician_Phone_Number
	{
		get
		{
			return this._Primary_Physician_Phone_Number;
		}
		set
		{
			if ((this._Primary_Physician_Phone_Number != value))
			{
				this._Primary_Physician_Phone_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Physician_Address", DbType="Char(31)")]
	public string Primary_Physician_Address
	{
		get
		{
			return this._Primary_Physician_Address;
		}
		set
		{
			if ((this._Primary_Physician_Address != value))
			{
				this._Primary_Physician_Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Physician_City", DbType="Char(25)")]
	public string Primary_Physician_City
	{
		get
		{
			return this._Primary_Physician_City;
		}
		set
		{
			if ((this._Primary_Physician_City != value))
			{
				this._Primary_Physician_City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Physician_State_Code", DbType="Char(3)")]
	public string Primary_Physician_State_Code
	{
		get
		{
			return this._Primary_Physician_State_Code;
		}
		set
		{
			if ((this._Primary_Physician_State_Code != value))
			{
				this._Primary_Physician_State_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Physician_ZipCode", DbType="Char(11)")]
	public string Primary_Physician_ZipCode
	{
		get
		{
			return this._Primary_Physician_ZipCode;
		}
		set
		{
			if ((this._Primary_Physician_ZipCode != value))
			{
				this._Primary_Physician_ZipCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_Name", DbType="VarChar(30)")]
	public string Primary_Plan_Name
	{
		get
		{
			return this._Primary_Plan_Name;
		}
		set
		{
			if ((this._Primary_Plan_Name != value))
			{
				this._Primary_Plan_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Policy_Number", DbType="VarChar(19)")]
	public string Primary_Policy_Number
	{
		get
		{
			return this._Primary_Policy_Number;
		}
		set
		{
			if ((this._Primary_Policy_Number != value))
			{
				this._Primary_Policy_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Group_Number", DbType="VarChar(19)")]
	public string Primary_Group_Number
	{
		get
		{
			return this._Primary_Group_Number;
		}
		set
		{
			if ((this._Primary_Group_Number != value))
			{
				this._Primary_Group_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_Code", DbType="Char(7)")]
	public string Primary_Plan_Code
	{
		get
		{
			return this._Primary_Plan_Code;
		}
		set
		{
			if ((this._Primary_Plan_Code != value))
			{
				this._Primary_Plan_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_Address", DbType="Char(31)")]
	public string Primary_Plan_Address
	{
		get
		{
			return this._Primary_Plan_Address;
		}
		set
		{
			if ((this._Primary_Plan_Address != value))
			{
				this._Primary_Plan_Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_State_Code", DbType="Char(3)")]
	public string Primary_Plan_State_Code
	{
		get
		{
			return this._Primary_Plan_State_Code;
		}
		set
		{
			if ((this._Primary_Plan_State_Code != value))
			{
				this._Primary_Plan_State_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_ZipCode", DbType="Char(11)")]
	public string Primary_Plan_ZipCode
	{
		get
		{
			return this._Primary_Plan_ZipCode;
		}
		set
		{
			if ((this._Primary_Plan_ZipCode != value))
			{
				this._Primary_Plan_ZipCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_Phone", DbType="Char(11)")]
	public string Primary_Plan_Phone
	{
		get
		{
			return this._Primary_Plan_Phone;
		}
		set
		{
			if ((this._Primary_Plan_Phone != value))
			{
				this._Primary_Plan_Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_Effective_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Primary_Plan_Effective_Date
	{
		get
		{
			return this._Primary_Plan_Effective_Date;
		}
		set
		{
			if ((this._Primary_Plan_Effective_Date != value))
			{
				this._Primary_Plan_Effective_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_Expiration_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Primary_Plan_Expiration_Date
	{
		get
		{
			return this._Primary_Plan_Expiration_Date;
		}
		set
		{
			if ((this._Primary_Plan_Expiration_Date != value))
			{
				this._Primary_Plan_Expiration_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_Name", DbType="VarChar(30)")]
	public string Secondary_Plan_Name
	{
		get
		{
			return this._Secondary_Plan_Name;
		}
		set
		{
			if ((this._Secondary_Plan_Name != value))
			{
				this._Secondary_Plan_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Policy_Number", DbType="VarChar(19)")]
	public string Secondary_Policy_Number
	{
		get
		{
			return this._Secondary_Policy_Number;
		}
		set
		{
			if ((this._Secondary_Policy_Number != value))
			{
				this._Secondary_Policy_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Group_Number", DbType="VarChar(19)")]
	public string Secondary_Group_Number
	{
		get
		{
			return this._Secondary_Group_Number;
		}
		set
		{
			if ((this._Secondary_Group_Number != value))
			{
				this._Secondary_Group_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_Code", DbType="Char(7)")]
	public string Secondary_Plan_Code
	{
		get
		{
			return this._Secondary_Plan_Code;
		}
		set
		{
			if ((this._Secondary_Plan_Code != value))
			{
				this._Secondary_Plan_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_Address", DbType="Char(31)")]
	public string Secondary_Plan_Address
	{
		get
		{
			return this._Secondary_Plan_Address;
		}
		set
		{
			if ((this._Secondary_Plan_Address != value))
			{
				this._Secondary_Plan_Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_State_Code", DbType="Char(3)")]
	public string Secondary_Plan_State_Code
	{
		get
		{
			return this._Secondary_Plan_State_Code;
		}
		set
		{
			if ((this._Secondary_Plan_State_Code != value))
			{
				this._Secondary_Plan_State_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_ZipCode", DbType="Char(11)")]
	public string Secondary_Plan_ZipCode
	{
		get
		{
			return this._Secondary_Plan_ZipCode;
		}
		set
		{
			if ((this._Secondary_Plan_ZipCode != value))
			{
				this._Secondary_Plan_ZipCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_Phone", DbType="Char(11)")]
	public string Secondary_Plan_Phone
	{
		get
		{
			return this._Secondary_Plan_Phone;
		}
		set
		{
			if ((this._Secondary_Plan_Phone != value))
			{
				this._Secondary_Plan_Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_Effective_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Secondary_Plan_Effective_Date
	{
		get
		{
			return this._Secondary_Plan_Effective_Date;
		}
		set
		{
			if ((this._Secondary_Plan_Effective_Date != value))
			{
				this._Secondary_Plan_Effective_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_Expiration_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Secondary_Plan_Expiration_Date
	{
		get
		{
			return this._Secondary_Plan_Expiration_Date;
		}
		set
		{
			if ((this._Secondary_Plan_Expiration_Date != value))
			{
				this._Secondary_Plan_Expiration_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Plan_City", DbType="Char(31)")]
	public string Primary_Plan_City
	{
		get
		{
			return this._Primary_Plan_City;
		}
		set
		{
			if ((this._Primary_Plan_City != value))
			{
				this._Primary_Plan_City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary_Plan_City", DbType="Char(31)")]
	public string Secondary_Plan_City
	{
		get
		{
			return this._Secondary_Plan_City;
		}
		set
		{
			if ((this._Secondary_Plan_City != value))
			{
				this._Secondary_Plan_City = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_VAEP_Records_AuditTrail")]
public partial class AS_Alere_VAEP_Records_AuditTrail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _RecordID;
	
	private string _PatientID;
	
	private string _CreatedBy;
	
	private string _WorkflowState;
	
	private string _NoteColumn;
	
	private string _DetailApproverNoteColumn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRecordIDChanging(string value);
    partial void OnRecordIDChanged();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnWorkflowStateChanging(string value);
    partial void OnWorkflowStateChanged();
    partial void OnNoteColumnChanging(string value);
    partial void OnNoteColumnChanged();
    partial void OnDetailApproverNoteColumnChanging(string value);
    partial void OnDetailApproverNoteColumnChanged();
    #endregion
	
	public AS_Alere_VAEP_Records_AuditTrail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string RecordID
	{
		get
		{
			return this._RecordID;
		}
		set
		{
			if ((this._RecordID != value))
			{
				this.OnRecordIDChanging(value);
				this.SendPropertyChanging();
				this._RecordID = value;
				this.SendPropertyChanged("RecordID");
				this.OnRecordIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15)")]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(250)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowState", DbType="NVarChar(250)")]
	public string WorkflowState
	{
		get
		{
			return this._WorkflowState;
		}
		set
		{
			if ((this._WorkflowState != value))
			{
				this.OnWorkflowStateChanging(value);
				this.SendPropertyChanging();
				this._WorkflowState = value;
				this.SendPropertyChanged("WorkflowState");
				this.OnWorkflowStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteColumn", DbType="NVarChar(250)")]
	public string NoteColumn
	{
		get
		{
			return this._NoteColumn;
		}
		set
		{
			if ((this._NoteColumn != value))
			{
				this.OnNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._NoteColumn = value;
				this.SendPropertyChanged("NoteColumn");
				this.OnNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailApproverNoteColumn", DbType="NVarChar(250)")]
	public string DetailApproverNoteColumn
	{
		get
		{
			return this._DetailApproverNoteColumn;
		}
		set
		{
			if ((this._DetailApproverNoteColumn != value))
			{
				this.OnDetailApproverNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._DetailApproverNoteColumn = value;
				this.SendPropertyChanged("DetailApproverNoteColumn");
				this.OnDetailApproverNoteColumnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_VAEP_Details")]
public partial class AS_Alere_VAEP_Detail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _RecordID;
	
	private System.Nullable<bool> _Gender;
	
	private string _PrimaryPhone;
	
	private string _SecondaryPhone;
	
	private string _Email;
	
	private string _Caregiver;
	
	private string _CaregiverRelationship;
	
	private string _CaregiverPrimaryPhone;
	
	private string _CaregiverSecondaryPhone;
	
	private System.Nullable<bool> _CaregiverPOA;
	
	private string _Physician;
	
	private string _PhysicianFax;
	
	private string _PhysicianPhone;
	
	private string _ReportResultsTo;
	
	private string _ReportResultsToPhone;
	
	private string _ReportResultsToFax;
	
	private string _AfterHoursInstruction;
	
	private string _Clinic;
	
	private string _ClinicAddress;
	
	private string _ClinicCityStateZip;
	
	private string _ClinicPhone;
	
	private string _MeterType;
	
	private string _TestFrequency;
	
	private string _APLSDiscussion;
	
	private string _TestReportingInstruction;
	
	private System.Nullable<bool> _FaxAllResults;
	
	private System.Nullable<bool> _MBE;
	
	private System.Nullable<System.DateTime> _MBEDate;
	
	private string _SelectOptions;
	
	private System.Nullable<int> _RetestIn;
	
	private string _OtherOptions;
	
	private string _AuthorizedBy;
	
	private string _AuthorizedByTitle;
	
	private string _TakenBy;
	
	private string _TakenByTitle;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<System.TimeSpan> _Time;
	
	private string _Attempt;
	
	private System.Nullable<System.DateTime> _AttemptDate;
	
	private System.Nullable<System.TimeSpan> _AttemptTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(string value);
    partial void OnRecordIDChanged();
    partial void OnGenderChanging(System.Nullable<bool> value);
    partial void OnGenderChanged();
    partial void OnPrimaryPhoneChanging(string value);
    partial void OnPrimaryPhoneChanged();
    partial void OnSecondaryPhoneChanging(string value);
    partial void OnSecondaryPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCaregiverChanging(string value);
    partial void OnCaregiverChanged();
    partial void OnCaregiverRelationshipChanging(string value);
    partial void OnCaregiverRelationshipChanged();
    partial void OnCaregiverPrimaryPhoneChanging(string value);
    partial void OnCaregiverPrimaryPhoneChanged();
    partial void OnCaregiverSecondaryPhoneChanging(string value);
    partial void OnCaregiverSecondaryPhoneChanged();
    partial void OnCaregiverPOAChanging(System.Nullable<bool> value);
    partial void OnCaregiverPOAChanged();
    partial void OnPhysicianChanging(string value);
    partial void OnPhysicianChanged();
    partial void OnPhysicianFaxChanging(string value);
    partial void OnPhysicianFaxChanged();
    partial void OnPhysicianPhoneChanging(string value);
    partial void OnPhysicianPhoneChanged();
    partial void OnReportResultsToChanging(string value);
    partial void OnReportResultsToChanged();
    partial void OnReportResultsToPhoneChanging(string value);
    partial void OnReportResultsToPhoneChanged();
    partial void OnReportResultsToFaxChanging(string value);
    partial void OnReportResultsToFaxChanged();
    partial void OnAfterHoursInstructionChanging(string value);
    partial void OnAfterHoursInstructionChanged();
    partial void OnClinicChanging(string value);
    partial void OnClinicChanged();
    partial void OnClinicAddressChanging(string value);
    partial void OnClinicAddressChanged();
    partial void OnClinicCityStateZipChanging(string value);
    partial void OnClinicCityStateZipChanged();
    partial void OnClinicPhoneChanging(string value);
    partial void OnClinicPhoneChanged();
    partial void OnMeterTypeChanging(string value);
    partial void OnMeterTypeChanged();
    partial void OnTestFrequencyChanging(string value);
    partial void OnTestFrequencyChanged();
    partial void OnAPLSDiscussionChanging(string value);
    partial void OnAPLSDiscussionChanged();
    partial void OnTestReportingInstructionChanging(string value);
    partial void OnTestReportingInstructionChanged();
    partial void OnFaxAllResultsChanging(System.Nullable<bool> value);
    partial void OnFaxAllResultsChanged();
    partial void OnMBEChanging(System.Nullable<bool> value);
    partial void OnMBEChanged();
    partial void OnMBEDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMBEDateChanged();
    partial void OnSelectOptionsChanging(string value);
    partial void OnSelectOptionsChanged();
    partial void OnRetestInChanging(System.Nullable<int> value);
    partial void OnRetestInChanged();
    partial void OnOtherOptionsChanging(string value);
    partial void OnOtherOptionsChanged();
    partial void OnAuthorizedByChanging(string value);
    partial void OnAuthorizedByChanged();
    partial void OnAuthorizedByTitleChanging(string value);
    partial void OnAuthorizedByTitleChanged();
    partial void OnTakenByChanging(string value);
    partial void OnTakenByChanged();
    partial void OnTakenByTitleChanging(string value);
    partial void OnTakenByTitleChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnTimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTimeChanged();
    partial void OnAttemptChanging(string value);
    partial void OnAttemptChanged();
    partial void OnAttemptDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAttemptDateChanged();
    partial void OnAttemptTimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnAttemptTimeChanged();
    #endregion
	
	public AS_Alere_VAEP_Detail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string RecordID
	{
		get
		{
			return this._RecordID;
		}
		set
		{
			if ((this._RecordID != value))
			{
				this.OnRecordIDChanging(value);
				this.SendPropertyChanging();
				this._RecordID = value;
				this.SendPropertyChanged("RecordID");
				this.OnRecordIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
	public System.Nullable<bool> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPhone", DbType="NVarChar(100)")]
	public string PrimaryPhone
	{
		get
		{
			return this._PrimaryPhone;
		}
		set
		{
			if ((this._PrimaryPhone != value))
			{
				this.OnPrimaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._PrimaryPhone = value;
				this.SendPropertyChanged("PrimaryPhone");
				this.OnPrimaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPhone", DbType="NVarChar(100)")]
	public string SecondaryPhone
	{
		get
		{
			return this._SecondaryPhone;
		}
		set
		{
			if ((this._SecondaryPhone != value))
			{
				this.OnSecondaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._SecondaryPhone = value;
				this.SendPropertyChanged("SecondaryPhone");
				this.OnSecondaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caregiver", DbType="NVarChar(250)")]
	public string Caregiver
	{
		get
		{
			return this._Caregiver;
		}
		set
		{
			if ((this._Caregiver != value))
			{
				this.OnCaregiverChanging(value);
				this.SendPropertyChanging();
				this._Caregiver = value;
				this.SendPropertyChanged("Caregiver");
				this.OnCaregiverChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverRelationship", DbType="NVarChar(250)")]
	public string CaregiverRelationship
	{
		get
		{
			return this._CaregiverRelationship;
		}
		set
		{
			if ((this._CaregiverRelationship != value))
			{
				this.OnCaregiverRelationshipChanging(value);
				this.SendPropertyChanging();
				this._CaregiverRelationship = value;
				this.SendPropertyChanged("CaregiverRelationship");
				this.OnCaregiverRelationshipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverPrimaryPhone", DbType="NVarChar(100)")]
	public string CaregiverPrimaryPhone
	{
		get
		{
			return this._CaregiverPrimaryPhone;
		}
		set
		{
			if ((this._CaregiverPrimaryPhone != value))
			{
				this.OnCaregiverPrimaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._CaregiverPrimaryPhone = value;
				this.SendPropertyChanged("CaregiverPrimaryPhone");
				this.OnCaregiverPrimaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverSecondaryPhone", DbType="NVarChar(100)")]
	public string CaregiverSecondaryPhone
	{
		get
		{
			return this._CaregiverSecondaryPhone;
		}
		set
		{
			if ((this._CaregiverSecondaryPhone != value))
			{
				this.OnCaregiverSecondaryPhoneChanging(value);
				this.SendPropertyChanging();
				this._CaregiverSecondaryPhone = value;
				this.SendPropertyChanged("CaregiverSecondaryPhone");
				this.OnCaregiverSecondaryPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaregiverPOA", DbType="Bit")]
	public System.Nullable<bool> CaregiverPOA
	{
		get
		{
			return this._CaregiverPOA;
		}
		set
		{
			if ((this._CaregiverPOA != value))
			{
				this.OnCaregiverPOAChanging(value);
				this.SendPropertyChanging();
				this._CaregiverPOA = value;
				this.SendPropertyChanged("CaregiverPOA");
				this.OnCaregiverPOAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physician", DbType="NVarChar(250)")]
	public string Physician
	{
		get
		{
			return this._Physician;
		}
		set
		{
			if ((this._Physician != value))
			{
				this.OnPhysicianChanging(value);
				this.SendPropertyChanging();
				this._Physician = value;
				this.SendPropertyChanged("Physician");
				this.OnPhysicianChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicianFax", DbType="NVarChar(100)")]
	public string PhysicianFax
	{
		get
		{
			return this._PhysicianFax;
		}
		set
		{
			if ((this._PhysicianFax != value))
			{
				this.OnPhysicianFaxChanging(value);
				this.SendPropertyChanging();
				this._PhysicianFax = value;
				this.SendPropertyChanged("PhysicianFax");
				this.OnPhysicianFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicianPhone", DbType="NVarChar(100)")]
	public string PhysicianPhone
	{
		get
		{
			return this._PhysicianPhone;
		}
		set
		{
			if ((this._PhysicianPhone != value))
			{
				this.OnPhysicianPhoneChanging(value);
				this.SendPropertyChanging();
				this._PhysicianPhone = value;
				this.SendPropertyChanged("PhysicianPhone");
				this.OnPhysicianPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportResultsTo", DbType="NVarChar(250)")]
	public string ReportResultsTo
	{
		get
		{
			return this._ReportResultsTo;
		}
		set
		{
			if ((this._ReportResultsTo != value))
			{
				this.OnReportResultsToChanging(value);
				this.SendPropertyChanging();
				this._ReportResultsTo = value;
				this.SendPropertyChanged("ReportResultsTo");
				this.OnReportResultsToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportResultsToPhone", DbType="NVarChar(100)")]
	public string ReportResultsToPhone
	{
		get
		{
			return this._ReportResultsToPhone;
		}
		set
		{
			if ((this._ReportResultsToPhone != value))
			{
				this.OnReportResultsToPhoneChanging(value);
				this.SendPropertyChanging();
				this._ReportResultsToPhone = value;
				this.SendPropertyChanged("ReportResultsToPhone");
				this.OnReportResultsToPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportResultsToFax", DbType="NVarChar(100)")]
	public string ReportResultsToFax
	{
		get
		{
			return this._ReportResultsToFax;
		}
		set
		{
			if ((this._ReportResultsToFax != value))
			{
				this.OnReportResultsToFaxChanging(value);
				this.SendPropertyChanging();
				this._ReportResultsToFax = value;
				this.SendPropertyChanged("ReportResultsToFax");
				this.OnReportResultsToFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterHoursInstruction", DbType="NVarChar(250)")]
	public string AfterHoursInstruction
	{
		get
		{
			return this._AfterHoursInstruction;
		}
		set
		{
			if ((this._AfterHoursInstruction != value))
			{
				this.OnAfterHoursInstructionChanging(value);
				this.SendPropertyChanging();
				this._AfterHoursInstruction = value;
				this.SendPropertyChanged("AfterHoursInstruction");
				this.OnAfterHoursInstructionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clinic", DbType="NVarChar(250)")]
	public string Clinic
	{
		get
		{
			return this._Clinic;
		}
		set
		{
			if ((this._Clinic != value))
			{
				this.OnClinicChanging(value);
				this.SendPropertyChanging();
				this._Clinic = value;
				this.SendPropertyChanged("Clinic");
				this.OnClinicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicAddress", DbType="NVarChar(250)")]
	public string ClinicAddress
	{
		get
		{
			return this._ClinicAddress;
		}
		set
		{
			if ((this._ClinicAddress != value))
			{
				this.OnClinicAddressChanging(value);
				this.SendPropertyChanging();
				this._ClinicAddress = value;
				this.SendPropertyChanged("ClinicAddress");
				this.OnClinicAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicCityStateZip", DbType="NVarChar(250)")]
	public string ClinicCityStateZip
	{
		get
		{
			return this._ClinicCityStateZip;
		}
		set
		{
			if ((this._ClinicCityStateZip != value))
			{
				this.OnClinicCityStateZipChanging(value);
				this.SendPropertyChanging();
				this._ClinicCityStateZip = value;
				this.SendPropertyChanged("ClinicCityStateZip");
				this.OnClinicCityStateZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicPhone", DbType="NVarChar(100)")]
	public string ClinicPhone
	{
		get
		{
			return this._ClinicPhone;
		}
		set
		{
			if ((this._ClinicPhone != value))
			{
				this.OnClinicPhoneChanging(value);
				this.SendPropertyChanging();
				this._ClinicPhone = value;
				this.SendPropertyChanged("ClinicPhone");
				this.OnClinicPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterType", DbType="NVarChar(150)")]
	public string MeterType
	{
		get
		{
			return this._MeterType;
		}
		set
		{
			if ((this._MeterType != value))
			{
				this.OnMeterTypeChanging(value);
				this.SendPropertyChanging();
				this._MeterType = value;
				this.SendPropertyChanged("MeterType");
				this.OnMeterTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestFrequency", DbType="NVarChar(150)")]
	public string TestFrequency
	{
		get
		{
			return this._TestFrequency;
		}
		set
		{
			if ((this._TestFrequency != value))
			{
				this.OnTestFrequencyChanging(value);
				this.SendPropertyChanging();
				this._TestFrequency = value;
				this.SendPropertyChanged("TestFrequency");
				this.OnTestFrequencyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APLSDiscussion", DbType="NVarChar(150)")]
	public string APLSDiscussion
	{
		get
		{
			return this._APLSDiscussion;
		}
		set
		{
			if ((this._APLSDiscussion != value))
			{
				this.OnAPLSDiscussionChanging(value);
				this.SendPropertyChanging();
				this._APLSDiscussion = value;
				this.SendPropertyChanged("APLSDiscussion");
				this.OnAPLSDiscussionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestReportingInstruction", DbType="NVarChar(150)")]
	public string TestReportingInstruction
	{
		get
		{
			return this._TestReportingInstruction;
		}
		set
		{
			if ((this._TestReportingInstruction != value))
			{
				this.OnTestReportingInstructionChanging(value);
				this.SendPropertyChanging();
				this._TestReportingInstruction = value;
				this.SendPropertyChanged("TestReportingInstruction");
				this.OnTestReportingInstructionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxAllResults", DbType="Bit")]
	public System.Nullable<bool> FaxAllResults
	{
		get
		{
			return this._FaxAllResults;
		}
		set
		{
			if ((this._FaxAllResults != value))
			{
				this.OnFaxAllResultsChanging(value);
				this.SendPropertyChanging();
				this._FaxAllResults = value;
				this.SendPropertyChanged("FaxAllResults");
				this.OnFaxAllResultsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBE", DbType="Bit")]
	public System.Nullable<bool> MBE
	{
		get
		{
			return this._MBE;
		}
		set
		{
			if ((this._MBE != value))
			{
				this.OnMBEChanging(value);
				this.SendPropertyChanging();
				this._MBE = value;
				this.SendPropertyChanged("MBE");
				this.OnMBEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBEDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> MBEDate
	{
		get
		{
			return this._MBEDate;
		}
		set
		{
			if ((this._MBEDate != value))
			{
				this.OnMBEDateChanging(value);
				this.SendPropertyChanging();
				this._MBEDate = value;
				this.SendPropertyChanged("MBEDate");
				this.OnMBEDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectOptions", DbType="NVarChar(150)")]
	public string SelectOptions
	{
		get
		{
			return this._SelectOptions;
		}
		set
		{
			if ((this._SelectOptions != value))
			{
				this.OnSelectOptionsChanging(value);
				this.SendPropertyChanging();
				this._SelectOptions = value;
				this.SendPropertyChanged("SelectOptions");
				this.OnSelectOptionsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetestIn", DbType="Int")]
	public System.Nullable<int> RetestIn
	{
		get
		{
			return this._RetestIn;
		}
		set
		{
			if ((this._RetestIn != value))
			{
				this.OnRetestInChanging(value);
				this.SendPropertyChanging();
				this._RetestIn = value;
				this.SendPropertyChanged("RetestIn");
				this.OnRetestInChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherOptions", DbType="NVarChar(250)")]
	public string OtherOptions
	{
		get
		{
			return this._OtherOptions;
		}
		set
		{
			if ((this._OtherOptions != value))
			{
				this.OnOtherOptionsChanging(value);
				this.SendPropertyChanging();
				this._OtherOptions = value;
				this.SendPropertyChanged("OtherOptions");
				this.OnOtherOptionsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizedBy", DbType="NVarChar(250)")]
	public string AuthorizedBy
	{
		get
		{
			return this._AuthorizedBy;
		}
		set
		{
			if ((this._AuthorizedBy != value))
			{
				this.OnAuthorizedByChanging(value);
				this.SendPropertyChanging();
				this._AuthorizedBy = value;
				this.SendPropertyChanged("AuthorizedBy");
				this.OnAuthorizedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizedByTitle", DbType="NVarChar(100)")]
	public string AuthorizedByTitle
	{
		get
		{
			return this._AuthorizedByTitle;
		}
		set
		{
			if ((this._AuthorizedByTitle != value))
			{
				this.OnAuthorizedByTitleChanging(value);
				this.SendPropertyChanging();
				this._AuthorizedByTitle = value;
				this.SendPropertyChanged("AuthorizedByTitle");
				this.OnAuthorizedByTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakenBy", DbType="NVarChar(250)")]
	public string TakenBy
	{
		get
		{
			return this._TakenBy;
		}
		set
		{
			if ((this._TakenBy != value))
			{
				this.OnTakenByChanging(value);
				this.SendPropertyChanging();
				this._TakenBy = value;
				this.SendPropertyChanged("TakenBy");
				this.OnTakenByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakenByTitle", DbType="NVarChar(100)")]
	public string TakenByTitle
	{
		get
		{
			return this._TakenByTitle;
		}
		set
		{
			if ((this._TakenByTitle != value))
			{
				this.OnTakenByTitleChanging(value);
				this.SendPropertyChanging();
				this._TakenByTitle = value;
				this.SendPropertyChanged("TakenByTitle");
				this.OnTakenByTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Time")]
	public System.Nullable<System.TimeSpan> Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attempt", DbType="NVarChar(250)")]
	public string Attempt
	{
		get
		{
			return this._Attempt;
		}
		set
		{
			if ((this._Attempt != value))
			{
				this.OnAttemptChanging(value);
				this.SendPropertyChanging();
				this._Attempt = value;
				this.SendPropertyChanged("Attempt");
				this.OnAttemptChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttemptDate", DbType="Date")]
	public System.Nullable<System.DateTime> AttemptDate
	{
		get
		{
			return this._AttemptDate;
		}
		set
		{
			if ((this._AttemptDate != value))
			{
				this.OnAttemptDateChanging(value);
				this.SendPropertyChanging();
				this._AttemptDate = value;
				this.SendPropertyChanged("AttemptDate");
				this.OnAttemptDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttemptTime", DbType="Time")]
	public System.Nullable<System.TimeSpan> AttemptTime
	{
		get
		{
			return this._AttemptTime;
		}
		set
		{
			if ((this._AttemptTime != value))
			{
				this.OnAttemptTimeChanging(value);
				this.SendPropertyChanging();
				this._AttemptTime = value;
				this.SendPropertyChanged("AttemptTime");
				this.OnAttemptTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
