#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TWO")]
public partial class PresidioApprovalsDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAS_Presidio_ApprovalLevel(AS_Presidio_ApprovalLevel instance);
  partial void UpdateAS_Presidio_ApprovalLevel(AS_Presidio_ApprovalLevel instance);
  partial void DeleteAS_Presidio_ApprovalLevel(AS_Presidio_ApprovalLevel instance);
  partial void InsertAS_Presidio_ApprovalLevel_User(AS_Presidio_ApprovalLevel_User instance);
  partial void UpdateAS_Presidio_ApprovalLevel_User(AS_Presidio_ApprovalLevel_User instance);
  partial void DeleteAS_Presidio_ApprovalLevel_User(AS_Presidio_ApprovalLevel_User instance);
  partial void InsertAS_Presidio_Approval(AS_Presidio_Approval instance);
  partial void UpdateAS_Presidio_Approval(AS_Presidio_Approval instance);
  partial void DeleteAS_Presidio_Approval(AS_Presidio_Approval instance);
  #endregion
	
	public PresidioApprovalsDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TWOConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PresidioApprovalsDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PresidioApprovalsDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PresidioApprovalsDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PresidioApprovalsDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AS_Presidio_ApprovalLevel> AS_Presidio_ApprovalLevels
	{
		get
		{
			return this.GetTable<AS_Presidio_ApprovalLevel>();
		}
	}
	
	public System.Data.Linq.Table<AS_Presidio_ApprovalLevel_User> AS_Presidio_ApprovalLevel_Users
	{
		get
		{
			return this.GetTable<AS_Presidio_ApprovalLevel_User>();
		}
	}
	
	public System.Data.Linq.Table<AS_Presidio_Approval> AS_Presidio_Approvals
	{
		get
		{
			return this.GetTable<AS_Presidio_Approval>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Presidio_ApprovalLevels")]
public partial class AS_Presidio_ApprovalLevel : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ApprovalLevel;
	
	private string _ApprovalArea;
	
	private string _ApprovalType;
	
	private string _ApprovalLevelName;
	
	private System.Nullable<decimal> _ApprovalAmountThreshold;
	
	private System.Nullable<bool> _ApprovalOverride;
	
	private System.Nullable<bool> _ApprovalRequired;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApprovalLevelChanging(int value);
    partial void OnApprovalLevelChanged();
    partial void OnApprovalAreaChanging(string value);
    partial void OnApprovalAreaChanged();
    partial void OnApprovalTypeChanging(string value);
    partial void OnApprovalTypeChanged();
    partial void OnApprovalLevelNameChanging(string value);
    partial void OnApprovalLevelNameChanged();
    partial void OnApprovalAmountThresholdChanging(System.Nullable<decimal> value);
    partial void OnApprovalAmountThresholdChanged();
    partial void OnApprovalOverrideChanging(System.Nullable<bool> value);
    partial void OnApprovalOverrideChanged();
    partial void OnApprovalRequiredChanging(System.Nullable<bool> value);
    partial void OnApprovalRequiredChanged();
    #endregion
	
	public AS_Presidio_ApprovalLevel()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalLevel", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ApprovalLevel
	{
		get
		{
			return this._ApprovalLevel;
		}
		set
		{
			if ((this._ApprovalLevel != value))
			{
				this.OnApprovalLevelChanging(value);
				this.SendPropertyChanging();
				this._ApprovalLevel = value;
				this.SendPropertyChanged("ApprovalLevel");
				this.OnApprovalLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalArea", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ApprovalArea
	{
		get
		{
			return this._ApprovalArea;
		}
		set
		{
			if ((this._ApprovalArea != value))
			{
				this.OnApprovalAreaChanging(value);
				this.SendPropertyChanging();
				this._ApprovalArea = value;
				this.SendPropertyChanged("ApprovalArea");
				this.OnApprovalAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ApprovalType
	{
		get
		{
			return this._ApprovalType;
		}
		set
		{
			if ((this._ApprovalType != value))
			{
				this.OnApprovalTypeChanging(value);
				this.SendPropertyChanging();
				this._ApprovalType = value;
				this.SendPropertyChanged("ApprovalType");
				this.OnApprovalTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalLevelName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string ApprovalLevelName
	{
		get
		{
			return this._ApprovalLevelName;
		}
		set
		{
			if ((this._ApprovalLevelName != value))
			{
				this.OnApprovalLevelNameChanging(value);
				this.SendPropertyChanging();
				this._ApprovalLevelName = value;
				this.SendPropertyChanged("ApprovalLevelName");
				this.OnApprovalLevelNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalAmountThreshold", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> ApprovalAmountThreshold
	{
		get
		{
			return this._ApprovalAmountThreshold;
		}
		set
		{
			if ((this._ApprovalAmountThreshold != value))
			{
				this.OnApprovalAmountThresholdChanging(value);
				this.SendPropertyChanging();
				this._ApprovalAmountThreshold = value;
				this.SendPropertyChanged("ApprovalAmountThreshold");
				this.OnApprovalAmountThresholdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalOverride", DbType="Bit")]
	public System.Nullable<bool> ApprovalOverride
	{
		get
		{
			return this._ApprovalOverride;
		}
		set
		{
			if ((this._ApprovalOverride != value))
			{
				this.OnApprovalOverrideChanging(value);
				this.SendPropertyChanging();
				this._ApprovalOverride = value;
				this.SendPropertyChanged("ApprovalOverride");
				this.OnApprovalOverrideChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalRequired", DbType="Bit")]
	public System.Nullable<bool> ApprovalRequired
	{
		get
		{
			return this._ApprovalRequired;
		}
		set
		{
			if ((this._ApprovalRequired != value))
			{
				this.OnApprovalRequiredChanging(value);
				this.SendPropertyChanging();
				this._ApprovalRequired = value;
				this.SendPropertyChanged("ApprovalRequired");
				this.OnApprovalRequiredChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Presidio_ApprovalLevel_Users")]
public partial class AS_Presidio_ApprovalLevel_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ApprovalLevel;
	
	private string _ApprovalArea;
	
	private string _ApprovalType;
	
	private string _ApproverID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApprovalLevelChanging(int value);
    partial void OnApprovalLevelChanged();
    partial void OnApprovalAreaChanging(string value);
    partial void OnApprovalAreaChanged();
    partial void OnApprovalTypeChanging(string value);
    partial void OnApprovalTypeChanged();
    partial void OnApproverIDChanging(string value);
    partial void OnApproverIDChanged();
    #endregion
	
	public AS_Presidio_ApprovalLevel_User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalLevel", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ApprovalLevel
	{
		get
		{
			return this._ApprovalLevel;
		}
		set
		{
			if ((this._ApprovalLevel != value))
			{
				this.OnApprovalLevelChanging(value);
				this.SendPropertyChanging();
				this._ApprovalLevel = value;
				this.SendPropertyChanged("ApprovalLevel");
				this.OnApprovalLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalArea", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ApprovalArea
	{
		get
		{
			return this._ApprovalArea;
		}
		set
		{
			if ((this._ApprovalArea != value))
			{
				this.OnApprovalAreaChanging(value);
				this.SendPropertyChanging();
				this._ApprovalArea = value;
				this.SendPropertyChanged("ApprovalArea");
				this.OnApprovalAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ApprovalType
	{
		get
		{
			return this._ApprovalType;
		}
		set
		{
			if ((this._ApprovalType != value))
			{
				this.OnApprovalTypeChanging(value);
				this.SendPropertyChanging();
				this._ApprovalType = value;
				this.SendPropertyChanged("ApprovalType");
				this.OnApprovalTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApproverID", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ApproverID
	{
		get
		{
			return this._ApproverID;
		}
		set
		{
			if ((this._ApproverID != value))
			{
				this.OnApproverIDChanging(value);
				this.SendPropertyChanging();
				this._ApproverID = value;
				this.SendPropertyChanged("ApproverID");
				this.OnApproverIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Presidio_Approvals")]
public partial class AS_Presidio_Approval : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _RecordID;
	
	private string _WorkflowID;
	
	private string _ApprovalArea;
	
	private string _ApprovalType;
	
	private string _ApproverID;
	
	private System.Nullable<decimal> _Amount;
	
	private System.Nullable<int> _LastApprovalLevel;
	
	private string _WorkflowState;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(string value);
    partial void OnRecordIDChanged();
    partial void OnWorkflowIDChanging(string value);
    partial void OnWorkflowIDChanged();
    partial void OnApprovalAreaChanging(string value);
    partial void OnApprovalAreaChanged();
    partial void OnApprovalTypeChanging(string value);
    partial void OnApprovalTypeChanged();
    partial void OnApproverIDChanging(string value);
    partial void OnApproverIDChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnLastApprovalLevelChanging(System.Nullable<int> value);
    partial void OnLastApprovalLevelChanged();
    partial void OnWorkflowStateChanging(string value);
    partial void OnWorkflowStateChanged();
    #endregion
	
	public AS_Presidio_Approval()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string RecordID
	{
		get
		{
			return this._RecordID;
		}
		set
		{
			if ((this._RecordID != value))
			{
				this.OnRecordIDChanging(value);
				this.SendPropertyChanging();
				this._RecordID = value;
				this.SendPropertyChanged("RecordID");
				this.OnRecordIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowID", DbType="NVarChar(250)")]
	public string WorkflowID
	{
		get
		{
			return this._WorkflowID;
		}
		set
		{
			if ((this._WorkflowID != value))
			{
				this.OnWorkflowIDChanging(value);
				this.SendPropertyChanging();
				this._WorkflowID = value;
				this.SendPropertyChanged("WorkflowID");
				this.OnWorkflowIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalArea", DbType="NVarChar(50)")]
	public string ApprovalArea
	{
		get
		{
			return this._ApprovalArea;
		}
		set
		{
			if ((this._ApprovalArea != value))
			{
				this.OnApprovalAreaChanging(value);
				this.SendPropertyChanging();
				this._ApprovalArea = value;
				this.SendPropertyChanged("ApprovalArea");
				this.OnApprovalAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalType", DbType="NVarChar(50)")]
	public string ApprovalType
	{
		get
		{
			return this._ApprovalType;
		}
		set
		{
			if ((this._ApprovalType != value))
			{
				this.OnApprovalTypeChanging(value);
				this.SendPropertyChanging();
				this._ApprovalType = value;
				this.SendPropertyChanged("ApprovalType");
				this.OnApprovalTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApproverID", DbType="NVarChar(250)")]
	public string ApproverID
	{
		get
		{
			return this._ApproverID;
		}
		set
		{
			if ((this._ApproverID != value))
			{
				this.OnApproverIDChanging(value);
				this.SendPropertyChanging();
				this._ApproverID = value;
				this.SendPropertyChanged("ApproverID");
				this.OnApproverIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastApprovalLevel", DbType="Int")]
	public System.Nullable<int> LastApprovalLevel
	{
		get
		{
			return this._LastApprovalLevel;
		}
		set
		{
			if ((this._LastApprovalLevel != value))
			{
				this.OnLastApprovalLevelChanging(value);
				this.SendPropertyChanging();
				this._LastApprovalLevel = value;
				this.SendPropertyChanged("LastApprovalLevel");
				this.OnLastApprovalLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowState", DbType="NVarChar(50)")]
	public string WorkflowState
	{
		get
		{
			return this._WorkflowState;
		}
		set
		{
			if ((this._WorkflowState != value))
			{
				this.OnWorkflowStateChanging(value);
				this.SendPropertyChanging();
				this._WorkflowState = value;
				this.SendPropertyChanged("WorkflowState");
				this.OnWorkflowStateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
