//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TWOModel", "FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TWOModel.ShareAThonDonation), "ShareAThonDonationFrequency", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TWOModel.ShareAThonDonationFrequency), true)]
[assembly: EdmRelationshipAttribute("TWOModel", "FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonDonation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TWOModel.ShareAThonDonation), "ShareAThonOfferLine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TWOModel.ShareAThonOfferLine), true)]

#endregion

namespace TWOModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TWOEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TWOEntities object using the connection string found in the 'TWOEntities' section of the application configuration file.
        /// </summary>
        public TWOEntities() : base("name=TWOEntities", "TWOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TWOEntities object.
        /// </summary>
        public TWOEntities(string connectionString) : base(connectionString, "TWOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TWOEntities object.
        /// </summary>
        public TWOEntities(EntityConnection connection) : base(connection, "TWOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShareAThonDonation> ShareAThonDonations
        {
            get
            {
                if ((_ShareAThonDonations == null))
                {
                    _ShareAThonDonations = base.CreateObjectSet<ShareAThonDonation>("ShareAThonDonations");
                }
                return _ShareAThonDonations;
            }
        }
        private ObjectSet<ShareAThonDonation> _ShareAThonDonations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShareAThonDonationFrequency> ShareAThonDonationFrequencies
        {
            get
            {
                if ((_ShareAThonDonationFrequencies == null))
                {
                    _ShareAThonDonationFrequencies = base.CreateObjectSet<ShareAThonDonationFrequency>("ShareAThonDonationFrequencies");
                }
                return _ShareAThonDonationFrequencies;
            }
        }
        private ObjectSet<ShareAThonDonationFrequency> _ShareAThonDonationFrequencies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShareAThonOfferLine> ShareAThonOfferLines
        {
            get
            {
                if ((_ShareAThonOfferLines == null))
                {
                    _ShareAThonOfferLines = base.CreateObjectSet<ShareAThonOfferLine>("ShareAThonOfferLines");
                }
                return _ShareAThonOfferLines;
            }
        }
        private ObjectSet<ShareAThonOfferLine> _ShareAThonOfferLines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderDetail> OrderDetails
        {
            get
            {
                if ((_OrderDetails == null))
                {
                    _OrderDetails = base.CreateObjectSet<OrderDetail>("OrderDetails");
                }
                return _OrderDetails;
            }
        }
        private ObjectSet<OrderDetail> _OrderDetails;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShareAThonDonations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShareAThonDonations(ShareAThonDonation shareAThonDonation)
        {
            base.AddObject("ShareAThonDonations", shareAThonDonation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShareAThonDonationFrequencies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShareAThonDonationFrequencies(ShareAThonDonationFrequency shareAThonDonationFrequency)
        {
            base.AddObject("ShareAThonDonationFrequencies", shareAThonDonationFrequency);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShareAThonOfferLines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShareAThonOfferLines(ShareAThonOfferLine shareAThonOfferLine)
        {
            base.AddObject("ShareAThonOfferLines", shareAThonOfferLine);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderDetails(OrderDetail orderDetail)
        {
            base.AddObject("OrderDetails", orderDetail);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TWOModel", Name="OrderDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderDetail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static OrderDetail CreateOrderDetail(global::System.Int32 id)
        {
            OrderDetail orderDetail = new OrderDetail();
            orderDetail.Id = id;
            return orderDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrdDate
        {
            get
            {
                return _OrdDate;
            }
            set
            {
                OnOrdDateChanging(value);
                ReportPropertyChanging("OrdDate");
                _OrdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrdDate");
                OnOrdDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrdDate;
        partial void OnOrdDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrdDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormData
        {
            get
            {
                return _FormData;
            }
            set
            {
                OnFormDataChanging(value);
                ReportPropertyChanging("FormData");
                _FormData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormData");
                OnFormDataChanged();
            }
        }
        private global::System.String _FormData;
        partial void OnFormDataChanging(global::System.String value);
        partial void OnFormDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrdNo
        {
            get
            {
                return _OrdNo;
            }
            set
            {
                OnOrdNoChanging(value);
                ReportPropertyChanging("OrdNo");
                _OrdNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrdNo");
                OnOrdNoChanged();
            }
        }
        private global::System.String _OrdNo;
        partial void OnOrdNoChanging(global::System.String value);
        partial void OnOrdNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Operator
        {
            get
            {
                return _Operator;
            }
            set
            {
                OnOperatorChanging(value);
                ReportPropertyChanging("Operator");
                _Operator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Operator");
                OnOperatorChanged();
            }
        }
        private global::System.String _Operator;
        partial void OnOperatorChanging(global::System.String value);
        partial void OnOperatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OrdTotal
        {
            get
            {
                return _OrdTotal;
            }
            set
            {
                OnOrdTotalChanging(value);
                ReportPropertyChanging("OrdTotal");
                _OrdTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrdTotal");
                OnOrdTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _OrdTotal;
        partial void OnOrdTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnOrdTotalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TWOModel", Name="ShareAThonDonation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShareAThonDonation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShareAThonDonation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        public static ShareAThonDonation CreateShareAThonDonation(global::System.Int32 id, global::System.String customerId, global::System.String orderId)
        {
            ShareAThonDonation shareAThonDonation = new ShareAThonDonation();
            shareAThonDonation.Id = id;
            shareAThonDonation.CustomerId = customerId;
            shareAThonDonation.OrderId = orderId;
            return shareAThonDonation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private global::System.String _CustomerId;
        partial void OnCustomerIdChanging(global::System.String value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrentlyDonorOf
        {
            get
            {
                return _CurrentlyDonorOf;
            }
            set
            {
                OnCurrentlyDonorOfChanging(value);
                ReportPropertyChanging("CurrentlyDonorOf");
                _CurrentlyDonorOf = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentlyDonorOf");
                OnCurrentlyDonorOfChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrentlyDonorOf;
        partial void OnCurrentlyDonorOfChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrentlyDonorOfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InitialChargeOn
        {
            get
            {
                return _InitialChargeOn;
            }
            set
            {
                OnInitialChargeOnChanging(value);
                ReportPropertyChanging("InitialChargeOn");
                _InitialChargeOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InitialChargeOn");
                OnInitialChargeOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _InitialChargeOn;
        partial void OnInitialChargeOnChanging(Nullable<global::System.DateTime> value);
        partial void OnInitialChargeOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DonationAmount
        {
            get
            {
                return _DonationAmount;
            }
            set
            {
                OnDonationAmountChanging(value);
                ReportPropertyChanging("DonationAmount");
                _DonationAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonationAmount");
                OnDonationAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _DonationAmount;
        partial void OnDonationAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnDonationAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> IncreasingTo
        {
            get
            {
                return _IncreasingTo;
            }
            set
            {
                OnIncreasingToChanging(value);
                ReportPropertyChanging("IncreasingTo");
                _IncreasingTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncreasingTo");
                OnIncreasingToChanged();
            }
        }
        private Nullable<global::System.Decimal> _IncreasingTo;
        partial void OnIncreasingToChanging(Nullable<global::System.Decimal> value);
        partial void OnIncreasingToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DayToChargeMonthly
        {
            get
            {
                return _DayToChargeMonthly;
            }
            set
            {
                OnDayToChargeMonthlyChanging(value);
                ReportPropertyChanging("DayToChargeMonthly");
                _DayToChargeMonthly = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayToChargeMonthly");
                OnDayToChargeMonthlyChanged();
            }
        }
        private Nullable<global::System.Int32> _DayToChargeMonthly;
        partial void OnDayToChargeMonthlyChanging(Nullable<global::System.Int32> value);
        partial void OnDayToChargeMonthlyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.String _OrderId;
        partial void OnOrderIdChanging(global::System.String value);
        partial void OnOrderIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TWOModel", "FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonationFrequency")]
        public EntityCollection<ShareAThonDonationFrequency> ShareAThonDonationFrequencies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ShareAThonDonationFrequency>("TWOModel.FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonationFrequency");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ShareAThonDonationFrequency>("TWOModel.FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonationFrequency", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TWOModel", "FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonOfferLine")]
        public EntityCollection<ShareAThonOfferLine> ShareAThonOfferLines
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ShareAThonOfferLine>("TWOModel.FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonOfferLine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ShareAThonOfferLine>("TWOModel.FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonOfferLine", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TWOModel", Name="ShareAThonDonationFrequency")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShareAThonDonationFrequency : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShareAThonDonationFrequency object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="dueDate">Initial value of the DueDate property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="shareAThonDonationId">Initial value of the ShareAThonDonationId property.</param>
        public static ShareAThonDonationFrequency CreateShareAThonDonationFrequency(global::System.Int32 id, global::System.String orderId, global::System.DateTime dueDate, global::System.Decimal amount, global::System.String status, global::System.Int32 shareAThonDonationId)
        {
            ShareAThonDonationFrequency shareAThonDonationFrequency = new ShareAThonDonationFrequency();
            shareAThonDonationFrequency.Id = id;
            shareAThonDonationFrequency.OrderId = orderId;
            shareAThonDonationFrequency.DueDate = dueDate;
            shareAThonDonationFrequency.Amount = amount;
            shareAThonDonationFrequency.Status = status;
            shareAThonDonationFrequency.ShareAThonDonationId = shareAThonDonationId;
            return shareAThonDonationFrequency;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.String _OrderId;
        partial void OnOrderIdChanging(global::System.String value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShareAThonDonationId
        {
            get
            {
                return _ShareAThonDonationId;
            }
            set
            {
                OnShareAThonDonationIdChanging(value);
                ReportPropertyChanging("ShareAThonDonationId");
                _ShareAThonDonationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShareAThonDonationId");
                OnShareAThonDonationIdChanged();
            }
        }
        private global::System.Int32 _ShareAThonDonationId;
        partial void OnShareAThonDonationIdChanging(global::System.Int32 value);
        partial void OnShareAThonDonationIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TWOModel", "FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonation")]
        public ShareAThonDonation ShareAThonDonation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ShareAThonDonation> ShareAThonDonationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonDonationFrequency_ShareAThonDonation", "ShareAThonDonation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TWOModel", Name="ShareAThonOfferLine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShareAThonOfferLine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShareAThonOfferLine object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="offerNo">Initial value of the OfferNo property.</param>
        /// <param name="qty">Initial value of the Qty property.</param>
        /// <param name="shareAThonDonationId">Initial value of the ShareAThonDonationId property.</param>
        public static ShareAThonOfferLine CreateShareAThonOfferLine(global::System.Int32 id, global::System.String orderId, global::System.String offerNo, global::System.Int32 qty, global::System.Int32 shareAThonDonationId)
        {
            ShareAThonOfferLine shareAThonOfferLine = new ShareAThonOfferLine();
            shareAThonOfferLine.Id = id;
            shareAThonOfferLine.OrderId = orderId;
            shareAThonOfferLine.OfferNo = offerNo;
            shareAThonOfferLine.Qty = qty;
            shareAThonOfferLine.ShareAThonDonationId = shareAThonDonationId;
            return shareAThonOfferLine;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.String _OrderId;
        partial void OnOrderIdChanging(global::System.String value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OfferNo
        {
            get
            {
                return _OfferNo;
            }
            set
            {
                if (_OfferNo != value)
                {
                    OnOfferNoChanging(value);
                    ReportPropertyChanging("OfferNo");
                    _OfferNo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OfferNo");
                    OnOfferNoChanged();
                }
            }
        }
        private global::System.String _OfferNo;
        partial void OnOfferNoChanging(global::System.String value);
        partial void OnOfferNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Qty
        {
            get
            {
                return _Qty;
            }
            set
            {
                if (_Qty != value)
                {
                    OnQtyChanging(value);
                    ReportPropertyChanging("Qty");
                    _Qty = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Qty");
                    OnQtyChanged();
                }
            }
        }
        private global::System.Int32 _Qty;
        partial void OnQtyChanging(global::System.Int32 value);
        partial void OnQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShareAThonDonationId
        {
            get
            {
                return _ShareAThonDonationId;
            }
            set
            {
                if (_ShareAThonDonationId != value)
                {
                    OnShareAThonDonationIdChanging(value);
                    ReportPropertyChanging("ShareAThonDonationId");
                    _ShareAThonDonationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ShareAThonDonationId");
                    OnShareAThonDonationIdChanged();
                }
            }
        }
        private global::System.Int32 _ShareAThonDonationId;
        partial void OnShareAThonDonationIdChanging(global::System.Int32 value);
        partial void OnShareAThonDonationIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TWOModel", "FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonDonation")]
        public ShareAThonDonation ShareAThonDonation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonDonation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonDonation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ShareAThonDonation> ShareAThonDonationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonDonation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ShareAThonDonation>("TWOModel.FK_ShareAThonOfferLines_ShareAThonDonation", "ShareAThonDonation", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
