#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TWO")]
public partial class ChargebackDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAS_GAIAM_Chargeback_Header(AS_GAIAM_Chargeback_Header instance);
  partial void UpdateAS_GAIAM_Chargeback_Header(AS_GAIAM_Chargeback_Header instance);
  partial void DeleteAS_GAIAM_Chargeback_Header(AS_GAIAM_Chargeback_Header instance);
  partial void InsertAS_GAIAM_Chargeback_Detail_Temp(AS_GAIAM_Chargeback_Detail_Temp instance);
  partial void UpdateAS_GAIAM_Chargeback_Detail_Temp(AS_GAIAM_Chargeback_Detail_Temp instance);
  partial void DeleteAS_GAIAM_Chargeback_Detail_Temp(AS_GAIAM_Chargeback_Detail_Temp instance);
  partial void InsertAS_GAIAM_Chargeback_Detail(AS_GAIAM_Chargeback_Detail instance);
  partial void UpdateAS_GAIAM_Chargeback_Detail(AS_GAIAM_Chargeback_Detail instance);
  partial void DeleteAS_GAIAM_Chargeback_Detail(AS_GAIAM_Chargeback_Detail instance);
  partial void InsertAS_GAIAM_Chargeback_ExpenseType(AS_GAIAM_Chargeback_ExpenseType instance);
  partial void UpdateAS_GAIAM_Chargeback_ExpenseType(AS_GAIAM_Chargeback_ExpenseType instance);
  partial void DeleteAS_GAIAM_Chargeback_ExpenseType(AS_GAIAM_Chargeback_ExpenseType instance);
  #endregion
	
	public ChargebackDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TWOConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ChargebackDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ChargebackDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ChargebackDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ChargebackDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AS_WF_VW_WorkflowDocument> AS_WF_VW_WorkflowDocuments
	{
		get
		{
			return this.GetTable<AS_WF_VW_WorkflowDocument>();
		}
	}
	
	public System.Data.Linq.Table<AS_GAIAM_Chargeback_Header> AS_GAIAM_Chargeback_Headers
	{
		get
		{
			return this.GetTable<AS_GAIAM_Chargeback_Header>();
		}
	}
	
	public System.Data.Linq.Table<AS_GAIAM_Chargeback_Detail_Temp> AS_GAIAM_Chargeback_Detail_Temps
	{
		get
		{
			return this.GetTable<AS_GAIAM_Chargeback_Detail_Temp>();
		}
	}
	
	public System.Data.Linq.Table<AS_GAIAM_Chargeback_Detail> AS_GAIAM_Chargeback_Details
	{
		get
		{
			return this.GetTable<AS_GAIAM_Chargeback_Detail>();
		}
	}
	
	public System.Data.Linq.Table<AS_GAIAM_Chargeback_ExpenseType> AS_GAIAM_Chargeback_ExpenseTypes
	{
		get
		{
			return this.GetTable<AS_GAIAM_Chargeback_ExpenseType>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_WorkflowDocuments")]
public partial class AS_WF_VW_WorkflowDocument
{
	
	private string _Status;
	
	private string _Doc_Type;
	
	private string _Document_Key;
	
	private string _Customer;
	
	private string _CreatedBy;
	
	public AS_WF_VW_WorkflowDocument()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Type", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
	public string Doc_Type
	{
		get
		{
			return this._Doc_Type;
		}
		set
		{
			if ((this._Doc_Type != value))
			{
				this._Doc_Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_Key", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Document_Key
	{
		get
		{
			return this._Document_Key;
		}
		set
		{
			if ((this._Document_Key != value))
			{
				this._Document_Key = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="NVarChar(50)")]
	public string Customer
	{
		get
		{
			return this._Customer;
		}
		set
		{
			if ((this._Customer != value))
			{
				this._Customer = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(250)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this._CreatedBy = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_GAIAM_Chargeback_Header")]
public partial class AS_GAIAM_Chargeback_Header : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _AuthorizationNumber;
	
	private string _AccountName;
	
	private string _GAIAMAccountNumber;
	
	private string _EventName;
	
	private string _AddressStreet;
	
	private string _AddressCity;
	
	private string _AddressState;
	
	private string _AddressZip;
	
	private string _AddressCountry;
	
	private string _Phone;
	
	private string _SalesPerson;
	
	private string _IndirectAccountName;
	
	private string _VendorID;
	
	private string _VendorName;
	
	private System.Nullable<System.DateTime> _DateStartEvent;
	
	private System.Nullable<System.DateTime> _DateEndEvent;
	
	private string _ExpenseType;
	
	private string _ExpenseSubType;
	
	private System.Nullable<bool> _IsExpenseStudioApproved;
	
	private System.Nullable<bool> _IsExpensePaidByInvoice;
	
	private System.Nullable<bool> _Estimate;
	
	private System.Nullable<decimal> _TotalAmount;
	
	private System.Nullable<decimal> _ClaimedAmount;
	
	private string _SpecialInstructions;
	
	private string _WorkflowState;
	
	private string _CreatedBy;
	
	private string _AttachedFilePath;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthorizationNumberChanging(string value);
    partial void OnAuthorizationNumberChanged();
    partial void OnAccountNameChanging(string value);
    partial void OnAccountNameChanged();
    partial void OnGAIAMAccountNumberChanging(string value);
    partial void OnGAIAMAccountNumberChanged();
    partial void OnEventNameChanging(string value);
    partial void OnEventNameChanged();
    partial void OnAddressStreetChanging(string value);
    partial void OnAddressStreetChanged();
    partial void OnAddressCityChanging(string value);
    partial void OnAddressCityChanged();
    partial void OnAddressStateChanging(string value);
    partial void OnAddressStateChanged();
    partial void OnAddressZipChanging(string value);
    partial void OnAddressZipChanged();
    partial void OnAddressCountryChanging(string value);
    partial void OnAddressCountryChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnSalesPersonChanging(string value);
    partial void OnSalesPersonChanged();
    partial void OnIndirectAccountNameChanging(string value);
    partial void OnIndirectAccountNameChanged();
    partial void OnVendorIDChanging(string value);
    partial void OnVendorIDChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnDateStartEventChanging(System.Nullable<System.DateTime> value);
    partial void OnDateStartEventChanged();
    partial void OnDateEndEventChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEndEventChanged();
    partial void OnExpenseTypeChanging(string value);
    partial void OnExpenseTypeChanged();
    partial void OnExpenseSubTypeChanging(string value);
    partial void OnExpenseSubTypeChanged();
    partial void OnIsExpenseStudioApprovedChanging(System.Nullable<bool> value);
    partial void OnIsExpenseStudioApprovedChanged();
    partial void OnIsExpensePaidByInvoiceChanging(System.Nullable<bool> value);
    partial void OnIsExpensePaidByInvoiceChanged();
    partial void OnEstimateChanging(System.Nullable<bool> value);
    partial void OnEstimateChanged();
    partial void OnTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountChanged();
    partial void OnClaimedAmountChanging(System.Nullable<decimal> value);
    partial void OnClaimedAmountChanged();
    partial void OnSpecialInstructionsChanging(string value);
    partial void OnSpecialInstructionsChanged();
    partial void OnWorkflowStateChanging(string value);
    partial void OnWorkflowStateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnAttachedFilePathChanging(string value);
    partial void OnAttachedFilePathChanged();
    #endregion
	
	public AS_GAIAM_Chargeback_Header()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizationNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string AuthorizationNumber
	{
		get
		{
			return this._AuthorizationNumber;
		}
		set
		{
			if ((this._AuthorizationNumber != value))
			{
				this.OnAuthorizationNumberChanging(value);
				this.SendPropertyChanging();
				this._AuthorizationNumber = value;
				this.SendPropertyChanged("AuthorizationNumber");
				this.OnAuthorizationNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="NVarChar(250)")]
	public string AccountName
	{
		get
		{
			return this._AccountName;
		}
		set
		{
			if ((this._AccountName != value))
			{
				this.OnAccountNameChanging(value);
				this.SendPropertyChanging();
				this._AccountName = value;
				this.SendPropertyChanged("AccountName");
				this.OnAccountNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GAIAMAccountNumber", DbType="NVarChar(250)")]
	public string GAIAMAccountNumber
	{
		get
		{
			return this._GAIAMAccountNumber;
		}
		set
		{
			if ((this._GAIAMAccountNumber != value))
			{
				this.OnGAIAMAccountNumberChanging(value);
				this.SendPropertyChanging();
				this._GAIAMAccountNumber = value;
				this.SendPropertyChanged("GAIAMAccountNumber");
				this.OnGAIAMAccountNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventName", DbType="NVarChar(250)")]
	public string EventName
	{
		get
		{
			return this._EventName;
		}
		set
		{
			if ((this._EventName != value))
			{
				this.OnEventNameChanging(value);
				this.SendPropertyChanging();
				this._EventName = value;
				this.SendPropertyChanged("EventName");
				this.OnEventNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressStreet", DbType="NVarChar(250)")]
	public string AddressStreet
	{
		get
		{
			return this._AddressStreet;
		}
		set
		{
			if ((this._AddressStreet != value))
			{
				this.OnAddressStreetChanging(value);
				this.SendPropertyChanging();
				this._AddressStreet = value;
				this.SendPropertyChanged("AddressStreet");
				this.OnAddressStreetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressCity", DbType="NVarChar(250)")]
	public string AddressCity
	{
		get
		{
			return this._AddressCity;
		}
		set
		{
			if ((this._AddressCity != value))
			{
				this.OnAddressCityChanging(value);
				this.SendPropertyChanging();
				this._AddressCity = value;
				this.SendPropertyChanged("AddressCity");
				this.OnAddressCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressState", DbType="NVarChar(250)")]
	public string AddressState
	{
		get
		{
			return this._AddressState;
		}
		set
		{
			if ((this._AddressState != value))
			{
				this.OnAddressStateChanging(value);
				this.SendPropertyChanging();
				this._AddressState = value;
				this.SendPropertyChanged("AddressState");
				this.OnAddressStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressZip", DbType="NVarChar(250)")]
	public string AddressZip
	{
		get
		{
			return this._AddressZip;
		}
		set
		{
			if ((this._AddressZip != value))
			{
				this.OnAddressZipChanging(value);
				this.SendPropertyChanging();
				this._AddressZip = value;
				this.SendPropertyChanged("AddressZip");
				this.OnAddressZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressCountry", DbType="NVarChar(250)")]
	public string AddressCountry
	{
		get
		{
			return this._AddressCountry;
		}
		set
		{
			if ((this._AddressCountry != value))
			{
				this.OnAddressCountryChanging(value);
				this.SendPropertyChanging();
				this._AddressCountry = value;
				this.SendPropertyChanged("AddressCountry");
				this.OnAddressCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(250)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPerson", DbType="NVarChar(250)")]
	public string SalesPerson
	{
		get
		{
			return this._SalesPerson;
		}
		set
		{
			if ((this._SalesPerson != value))
			{
				this.OnSalesPersonChanging(value);
				this.SendPropertyChanging();
				this._SalesPerson = value;
				this.SendPropertyChanged("SalesPerson");
				this.OnSalesPersonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndirectAccountName", DbType="NVarChar(250)")]
	public string IndirectAccountName
	{
		get
		{
			return this._IndirectAccountName;
		}
		set
		{
			if ((this._IndirectAccountName != value))
			{
				this.OnIndirectAccountNameChanging(value);
				this.SendPropertyChanging();
				this._IndirectAccountName = value;
				this.SendPropertyChanged("IndirectAccountName");
				this.OnIndirectAccountNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorID", DbType="NVarChar(250)")]
	public string VendorID
	{
		get
		{
			return this._VendorID;
		}
		set
		{
			if ((this._VendorID != value))
			{
				this.OnVendorIDChanging(value);
				this.SendPropertyChanging();
				this._VendorID = value;
				this.SendPropertyChanged("VendorID");
				this.OnVendorIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="NVarChar(250)")]
	public string VendorName
	{
		get
		{
			return this._VendorName;
		}
		set
		{
			if ((this._VendorName != value))
			{
				this.OnVendorNameChanging(value);
				this.SendPropertyChanging();
				this._VendorName = value;
				this.SendPropertyChanged("VendorName");
				this.OnVendorNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStartEvent", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateStartEvent
	{
		get
		{
			return this._DateStartEvent;
		}
		set
		{
			if ((this._DateStartEvent != value))
			{
				this.OnDateStartEventChanging(value);
				this.SendPropertyChanging();
				this._DateStartEvent = value;
				this.SendPropertyChanged("DateStartEvent");
				this.OnDateStartEventChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEndEvent", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateEndEvent
	{
		get
		{
			return this._DateEndEvent;
		}
		set
		{
			if ((this._DateEndEvent != value))
			{
				this.OnDateEndEventChanging(value);
				this.SendPropertyChanging();
				this._DateEndEvent = value;
				this.SendPropertyChanged("DateEndEvent");
				this.OnDateEndEventChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpenseType", DbType="NVarChar(250)")]
	public string ExpenseType
	{
		get
		{
			return this._ExpenseType;
		}
		set
		{
			if ((this._ExpenseType != value))
			{
				this.OnExpenseTypeChanging(value);
				this.SendPropertyChanging();
				this._ExpenseType = value;
				this.SendPropertyChanged("ExpenseType");
				this.OnExpenseTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpenseSubType", DbType="NVarChar(250)")]
	public string ExpenseSubType
	{
		get
		{
			return this._ExpenseSubType;
		}
		set
		{
			if ((this._ExpenseSubType != value))
			{
				this.OnExpenseSubTypeChanging(value);
				this.SendPropertyChanging();
				this._ExpenseSubType = value;
				this.SendPropertyChanged("ExpenseSubType");
				this.OnExpenseSubTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsExpenseStudioApproved", DbType="Bit")]
	public System.Nullable<bool> IsExpenseStudioApproved
	{
		get
		{
			return this._IsExpenseStudioApproved;
		}
		set
		{
			if ((this._IsExpenseStudioApproved != value))
			{
				this.OnIsExpenseStudioApprovedChanging(value);
				this.SendPropertyChanging();
				this._IsExpenseStudioApproved = value;
				this.SendPropertyChanged("IsExpenseStudioApproved");
				this.OnIsExpenseStudioApprovedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsExpensePaidByInvoice", DbType="Bit")]
	public System.Nullable<bool> IsExpensePaidByInvoice
	{
		get
		{
			return this._IsExpensePaidByInvoice;
		}
		set
		{
			if ((this._IsExpensePaidByInvoice != value))
			{
				this.OnIsExpensePaidByInvoiceChanging(value);
				this.SendPropertyChanging();
				this._IsExpensePaidByInvoice = value;
				this.SendPropertyChanged("IsExpensePaidByInvoice");
				this.OnIsExpensePaidByInvoiceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estimate", DbType="Bit")]
	public System.Nullable<bool> Estimate
	{
		get
		{
			return this._Estimate;
		}
		set
		{
			if ((this._Estimate != value))
			{
				this.OnEstimateChanging(value);
				this.SendPropertyChanging();
				this._Estimate = value;
				this.SendPropertyChanged("Estimate");
				this.OnEstimateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> TotalAmount
	{
		get
		{
			return this._TotalAmount;
		}
		set
		{
			if ((this._TotalAmount != value))
			{
				this.OnTotalAmountChanging(value);
				this.SendPropertyChanging();
				this._TotalAmount = value;
				this.SendPropertyChanged("TotalAmount");
				this.OnTotalAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimedAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> ClaimedAmount
	{
		get
		{
			return this._ClaimedAmount;
		}
		set
		{
			if ((this._ClaimedAmount != value))
			{
				this.OnClaimedAmountChanging(value);
				this.SendPropertyChanging();
				this._ClaimedAmount = value;
				this.SendPropertyChanged("ClaimedAmount");
				this.OnClaimedAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialInstructions", DbType="NVarChar(250)")]
	public string SpecialInstructions
	{
		get
		{
			return this._SpecialInstructions;
		}
		set
		{
			if ((this._SpecialInstructions != value))
			{
				this.OnSpecialInstructionsChanging(value);
				this.SendPropertyChanging();
				this._SpecialInstructions = value;
				this.SendPropertyChanged("SpecialInstructions");
				this.OnSpecialInstructionsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowState", DbType="NVarChar(250)")]
	public string WorkflowState
	{
		get
		{
			return this._WorkflowState;
		}
		set
		{
			if ((this._WorkflowState != value))
			{
				this.OnWorkflowStateChanging(value);
				this.SendPropertyChanging();
				this._WorkflowState = value;
				this.SendPropertyChanged("WorkflowState");
				this.OnWorkflowStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(250)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachedFilePath", DbType="NVarChar(250)")]
	public string AttachedFilePath
	{
		get
		{
			return this._AttachedFilePath;
		}
		set
		{
			if ((this._AttachedFilePath != value))
			{
				this.OnAttachedFilePathChanging(value);
				this.SendPropertyChanging();
				this._AttachedFilePath = value;
				this.SendPropertyChanged("AttachedFilePath");
				this.OnAttachedFilePathChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_GAIAM_Chargeback_Detail_Temp")]
public partial class AS_GAIAM_Chargeback_Detail_Temp : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _AuthorizationNumber;
	
	private string _GAIAMItemNumber;
	
	private string _TitlePromotion;
	
	private string _UPCCode;
	
	private string _Studio;
	
	private System.Nullable<decimal> _AmountPerUnit;
	
	private System.Nullable<int> _Quantity;
	
	private System.Nullable<decimal> _TotalAmount;
	
	private System.Nullable<decimal> _AuthorizedAmount;
	
	private string _InvalidText;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthorizationNumberChanging(string value);
    partial void OnAuthorizationNumberChanged();
    partial void OnGAIAMItemNumberChanging(string value);
    partial void OnGAIAMItemNumberChanged();
    partial void OnTitlePromotionChanging(string value);
    partial void OnTitlePromotionChanged();
    partial void OnUPCCodeChanging(string value);
    partial void OnUPCCodeChanged();
    partial void OnStudioChanging(string value);
    partial void OnStudioChanged();
    partial void OnAmountPerUnitChanging(System.Nullable<decimal> value);
    partial void OnAmountPerUnitChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    partial void OnTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountChanged();
    partial void OnAuthorizedAmountChanging(System.Nullable<decimal> value);
    partial void OnAuthorizedAmountChanged();
    partial void OnInvalidTextChanging(string value);
    partial void OnInvalidTextChanged();
    #endregion
	
	public AS_GAIAM_Chargeback_Detail_Temp()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizationNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string AuthorizationNumber
	{
		get
		{
			return this._AuthorizationNumber;
		}
		set
		{
			if ((this._AuthorizationNumber != value))
			{
				this.OnAuthorizationNumberChanging(value);
				this.SendPropertyChanging();
				this._AuthorizationNumber = value;
				this.SendPropertyChanged("AuthorizationNumber");
				this.OnAuthorizationNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GAIAMItemNumber", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string GAIAMItemNumber
	{
		get
		{
			return this._GAIAMItemNumber;
		}
		set
		{
			if ((this._GAIAMItemNumber != value))
			{
				this.OnGAIAMItemNumberChanging(value);
				this.SendPropertyChanging();
				this._GAIAMItemNumber = value;
				this.SendPropertyChanged("GAIAMItemNumber");
				this.OnGAIAMItemNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitlePromotion", DbType="NVarChar(250)")]
	public string TitlePromotion
	{
		get
		{
			return this._TitlePromotion;
		}
		set
		{
			if ((this._TitlePromotion != value))
			{
				this.OnTitlePromotionChanging(value);
				this.SendPropertyChanging();
				this._TitlePromotion = value;
				this.SendPropertyChanged("TitlePromotion");
				this.OnTitlePromotionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPCCode", DbType="NVarChar(250)")]
	public string UPCCode
	{
		get
		{
			return this._UPCCode;
		}
		set
		{
			if ((this._UPCCode != value))
			{
				this.OnUPCCodeChanging(value);
				this.SendPropertyChanging();
				this._UPCCode = value;
				this.SendPropertyChanged("UPCCode");
				this.OnUPCCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Studio", DbType="NVarChar(250)")]
	public string Studio
	{
		get
		{
			return this._Studio;
		}
		set
		{
			if ((this._Studio != value))
			{
				this.OnStudioChanging(value);
				this.SendPropertyChanging();
				this._Studio = value;
				this.SendPropertyChanged("Studio");
				this.OnStudioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountPerUnit", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> AmountPerUnit
	{
		get
		{
			return this._AmountPerUnit;
		}
		set
		{
			if ((this._AmountPerUnit != value))
			{
				this.OnAmountPerUnitChanging(value);
				this.SendPropertyChanging();
				this._AmountPerUnit = value;
				this.SendPropertyChanged("AmountPerUnit");
				this.OnAmountPerUnitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
	public System.Nullable<int> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> TotalAmount
	{
		get
		{
			return this._TotalAmount;
		}
		set
		{
			if ((this._TotalAmount != value))
			{
				this.OnTotalAmountChanging(value);
				this.SendPropertyChanging();
				this._TotalAmount = value;
				this.SendPropertyChanged("TotalAmount");
				this.OnTotalAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizedAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> AuthorizedAmount
	{
		get
		{
			return this._AuthorizedAmount;
		}
		set
		{
			if ((this._AuthorizedAmount != value))
			{
				this.OnAuthorizedAmountChanging(value);
				this.SendPropertyChanging();
				this._AuthorizedAmount = value;
				this.SendPropertyChanged("AuthorizedAmount");
				this.OnAuthorizedAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvalidText", DbType="NVarChar(50)")]
	public string InvalidText
	{
		get
		{
			return this._InvalidText;
		}
		set
		{
			if ((this._InvalidText != value))
			{
				this.OnInvalidTextChanging(value);
				this.SendPropertyChanging();
				this._InvalidText = value;
				this.SendPropertyChanged("InvalidText");
				this.OnInvalidTextChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_GAIAM_Chargeback_Detail")]
public partial class AS_GAIAM_Chargeback_Detail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _RecordID;
	
	private string _AuthorizationNumber;
	
	private string _GAIAMItemNumber;
	
	private string _TitlePromotion;
	
	private string _UPCCode;
	
	private string _Studio;
	
	private System.Nullable<decimal> _AmountPerUnit;
	
	private System.Nullable<int> _Quantity;
	
	private System.Nullable<decimal> _TotalAmount;
	
	private System.Nullable<decimal> _AuthorizedAmount;
	
	private string _InvalidText;
	
	private string _AccountNumber;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnAuthorizationNumberChanging(string value);
    partial void OnAuthorizationNumberChanged();
    partial void OnGAIAMItemNumberChanging(string value);
    partial void OnGAIAMItemNumberChanged();
    partial void OnTitlePromotionChanging(string value);
    partial void OnTitlePromotionChanged();
    partial void OnUPCCodeChanging(string value);
    partial void OnUPCCodeChanged();
    partial void OnStudioChanging(string value);
    partial void OnStudioChanged();
    partial void OnAmountPerUnitChanging(System.Nullable<decimal> value);
    partial void OnAmountPerUnitChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    partial void OnTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountChanged();
    partial void OnAuthorizedAmountChanging(System.Nullable<decimal> value);
    partial void OnAuthorizedAmountChanged();
    partial void OnInvalidTextChanging(string value);
    partial void OnInvalidTextChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    #endregion
	
	public AS_GAIAM_Chargeback_Detail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int RecordID
	{
		get
		{
			return this._RecordID;
		}
		set
		{
			if ((this._RecordID != value))
			{
				this.OnRecordIDChanging(value);
				this.SendPropertyChanging();
				this._RecordID = value;
				this.SendPropertyChanged("RecordID");
				this.OnRecordIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizationNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string AuthorizationNumber
	{
		get
		{
			return this._AuthorizationNumber;
		}
		set
		{
			if ((this._AuthorizationNumber != value))
			{
				this.OnAuthorizationNumberChanging(value);
				this.SendPropertyChanging();
				this._AuthorizationNumber = value;
				this.SendPropertyChanged("AuthorizationNumber");
				this.OnAuthorizationNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GAIAMItemNumber", DbType="NVarChar(250)")]
	public string GAIAMItemNumber
	{
		get
		{
			return this._GAIAMItemNumber;
		}
		set
		{
			if ((this._GAIAMItemNumber != value))
			{
				this.OnGAIAMItemNumberChanging(value);
				this.SendPropertyChanging();
				this._GAIAMItemNumber = value;
				this.SendPropertyChanged("GAIAMItemNumber");
				this.OnGAIAMItemNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitlePromotion", DbType="NVarChar(250)")]
	public string TitlePromotion
	{
		get
		{
			return this._TitlePromotion;
		}
		set
		{
			if ((this._TitlePromotion != value))
			{
				this.OnTitlePromotionChanging(value);
				this.SendPropertyChanging();
				this._TitlePromotion = value;
				this.SendPropertyChanged("TitlePromotion");
				this.OnTitlePromotionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPCCode", DbType="NVarChar(250)")]
	public string UPCCode
	{
		get
		{
			return this._UPCCode;
		}
		set
		{
			if ((this._UPCCode != value))
			{
				this.OnUPCCodeChanging(value);
				this.SendPropertyChanging();
				this._UPCCode = value;
				this.SendPropertyChanged("UPCCode");
				this.OnUPCCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Studio", DbType="NVarChar(250)")]
	public string Studio
	{
		get
		{
			return this._Studio;
		}
		set
		{
			if ((this._Studio != value))
			{
				this.OnStudioChanging(value);
				this.SendPropertyChanging();
				this._Studio = value;
				this.SendPropertyChanged("Studio");
				this.OnStudioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountPerUnit", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> AmountPerUnit
	{
		get
		{
			return this._AmountPerUnit;
		}
		set
		{
			if ((this._AmountPerUnit != value))
			{
				this.OnAmountPerUnitChanging(value);
				this.SendPropertyChanging();
				this._AmountPerUnit = value;
				this.SendPropertyChanged("AmountPerUnit");
				this.OnAmountPerUnitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
	public System.Nullable<int> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> TotalAmount
	{
		get
		{
			return this._TotalAmount;
		}
		set
		{
			if ((this._TotalAmount != value))
			{
				this.OnTotalAmountChanging(value);
				this.SendPropertyChanging();
				this._TotalAmount = value;
				this.SendPropertyChanged("TotalAmount");
				this.OnTotalAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizedAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> AuthorizedAmount
	{
		get
		{
			return this._AuthorizedAmount;
		}
		set
		{
			if ((this._AuthorizedAmount != value))
			{
				this.OnAuthorizedAmountChanging(value);
				this.SendPropertyChanging();
				this._AuthorizedAmount = value;
				this.SendPropertyChanged("AuthorizedAmount");
				this.OnAuthorizedAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvalidText", DbType="NVarChar(50)")]
	public string InvalidText
	{
		get
		{
			return this._InvalidText;
		}
		set
		{
			if ((this._InvalidText != value))
			{
				this.OnInvalidTextChanging(value);
				this.SendPropertyChanging();
				this._InvalidText = value;
				this.SendPropertyChanged("InvalidText");
				this.OnInvalidTextChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(50)")]
	public string AccountNumber
	{
		get
		{
			return this._AccountNumber;
		}
		set
		{
			if ((this._AccountNumber != value))
			{
				this.OnAccountNumberChanging(value);
				this.SendPropertyChanging();
				this._AccountNumber = value;
				this.SendPropertyChanged("AccountNumber");
				this.OnAccountNumberChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_GAIAM_Chargeback_ExpenseTypes")]
public partial class AS_GAIAM_Chargeback_ExpenseType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ExpenseType;
	
	private string _ExpenseSubType;
	
	private System.Nullable<int> _AccountIndex;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExpenseTypeChanging(string value);
    partial void OnExpenseTypeChanged();
    partial void OnExpenseSubTypeChanging(string value);
    partial void OnExpenseSubTypeChanged();
    partial void OnAccountIndexChanging(System.Nullable<int> value);
    partial void OnAccountIndexChanged();
    #endregion
	
	public AS_GAIAM_Chargeback_ExpenseType()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpenseType", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ExpenseType
	{
		get
		{
			return this._ExpenseType;
		}
		set
		{
			if ((this._ExpenseType != value))
			{
				this.OnExpenseTypeChanging(value);
				this.SendPropertyChanging();
				this._ExpenseType = value;
				this.SendPropertyChanged("ExpenseType");
				this.OnExpenseTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpenseSubType", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ExpenseSubType
	{
		get
		{
			return this._ExpenseSubType;
		}
		set
		{
			if ((this._ExpenseSubType != value))
			{
				this.OnExpenseSubTypeChanging(value);
				this.SendPropertyChanging();
				this._ExpenseSubType = value;
				this.SendPropertyChanged("ExpenseSubType");
				this.OnExpenseSubTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountIndex", DbType="Int")]
	public System.Nullable<int> AccountIndex
	{
		get
		{
			return this._AccountIndex;
		}
		set
		{
			if ((this._AccountIndex != value))
			{
				this.OnAccountIndexChanging(value);
				this.SendPropertyChanging();
				this._AccountIndex = value;
				this.SendPropertyChanged("AccountIndex");
				this.OnAccountIndexChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
