#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TWO")]
public partial class AlerePatientMailingDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAS_Alere_PMWF_OrderDetail(AS_Alere_PMWF_OrderDetail instance);
  partial void UpdateAS_Alere_PMWF_OrderDetail(AS_Alere_PMWF_OrderDetail instance);
  partial void DeleteAS_Alere_PMWF_OrderDetail(AS_Alere_PMWF_OrderDetail instance);
  partial void InsertAS_Alere_PMWF_BasicInformation(AS_Alere_PMWF_BasicInformation instance);
  partial void UpdateAS_Alere_PMWF_BasicInformation(AS_Alere_PMWF_BasicInformation instance);
  partial void DeleteAS_Alere_PMWF_BasicInformation(AS_Alere_PMWF_BasicInformation instance);
  partial void InsertAS_Alere_PMWF_PatientInformation(AS_Alere_PMWF_PatientInformation instance);
  partial void UpdateAS_Alere_PMWF_PatientInformation(AS_Alere_PMWF_PatientInformation instance);
  partial void DeleteAS_Alere_PMWF_PatientInformation(AS_Alere_PMWF_PatientInformation instance);
  partial void InsertAS_Alere_PMWF_Order(AS_Alere_PMWF_Order instance);
  partial void UpdateAS_Alere_PMWF_Order(AS_Alere_PMWF_Order instance);
  partial void DeleteAS_Alere_PMWF_Order(AS_Alere_PMWF_Order instance);
  partial void InsertAS_Alere_PMWF_ItemList(AS_Alere_PMWF_ItemList instance);
  partial void UpdateAS_Alere_PMWF_ItemList(AS_Alere_PMWF_ItemList instance);
  partial void DeleteAS_Alere_PMWF_ItemList(AS_Alere_PMWF_ItemList instance);
  #endregion
	
	public AlerePatientMailingDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TWOConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public AlerePatientMailingDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlerePatientMailingDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlerePatientMailingDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlerePatientMailingDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AS_Alere_PMWF_OrderDetail> AS_Alere_PMWF_OrderDetails
	{
		get
		{
			return this.GetTable<AS_Alere_PMWF_OrderDetail>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_PMWF_BasicInformation> AS_Alere_PMWF_BasicInformations
	{
		get
		{
			return this.GetTable<AS_Alere_PMWF_BasicInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_PMWF_PatientInformation> AS_Alere_PMWF_PatientInformations
	{
		get
		{
			return this.GetTable<AS_Alere_PMWF_PatientInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_PMWF_AlereBasicInformation> AS_WF_VW_PMWF_AlereBasicInformations
	{
		get
		{
			return this.GetTable<AS_WF_VW_PMWF_AlereBasicInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_PMWF_AlerePatientInformation> AS_WF_VW_PMWF_AlerePatientInformations
	{
		get
		{
			return this.GetTable<AS_WF_VW_PMWF_AlerePatientInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_PMWF_AlerePatientLookup> AS_WF_VW_PMWF_AlerePatientLookups
	{
		get
		{
			return this.GetTable<AS_WF_VW_PMWF_AlerePatientLookup>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_PMWF_Order> AS_Alere_PMWF_Orders
	{
		get
		{
			return this.GetTable<AS_Alere_PMWF_Order>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_PMWF_ItemList> AS_Alere_PMWF_ItemLists
	{
		get
		{
			return this.GetTable<AS_Alere_PMWF_ItemList>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_PMWF_OrderDetail")]
public partial class AS_Alere_PMWF_OrderDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _OrderID;
	
	private string _ItemSKU;
	
	private string _Description;
	
	private System.Nullable<int> _Quantity;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnOrderIDChanging(string value);
    partial void OnOrderIDChanged();
    partial void OnItemSKUChanging(string value);
    partial void OnItemSKUChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    #endregion
	
	public AS_Alere_PMWF_OrderDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemSKU", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ItemSKU
	{
		get
		{
			return this._ItemSKU;
		}
		set
		{
			if ((this._ItemSKU != value))
			{
				this.OnItemSKUChanging(value);
				this.SendPropertyChanging();
				this._ItemSKU = value;
				this.SendPropertyChanged("ItemSKU");
				this.OnItemSKUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(250)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
	public System.Nullable<int> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_PMWF_BasicInformation")]
public partial class AS_Alere_PMWF_BasicInformation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _OrderID;
	
	private string _FirstName;
	
	private string _LastName;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _CustomerClass;
	
	private System.Nullable<System.DateTime> _LastShipDate;
	
	private string _MeterType;
	
	private string _LancetType;
	
	private System.Nullable<System.DateTime> _DueDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnOrderIDChanging(string value);
    partial void OnOrderIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnCustomerClassChanging(string value);
    partial void OnCustomerClassChanged();
    partial void OnLastShipDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastShipDateChanged();
    partial void OnMeterTypeChanging(string value);
    partial void OnMeterTypeChanged();
    partial void OnLancetTypeChanging(string value);
    partial void OnLancetTypeChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    #endregion
	
	public AS_Alere_PMWF_BasicInformation()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(250)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(250)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerClass", DbType="NVarChar(50)")]
	public string CustomerClass
	{
		get
		{
			return this._CustomerClass;
		}
		set
		{
			if ((this._CustomerClass != value))
			{
				this.OnCustomerClassChanging(value);
				this.SendPropertyChanging();
				this._CustomerClass = value;
				this.SendPropertyChanged("CustomerClass");
				this.OnCustomerClassChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastShipDate", DbType="Date")]
	public System.Nullable<System.DateTime> LastShipDate
	{
		get
		{
			return this._LastShipDate;
		}
		set
		{
			if ((this._LastShipDate != value))
			{
				this.OnLastShipDateChanging(value);
				this.SendPropertyChanging();
				this._LastShipDate = value;
				this.SendPropertyChanged("LastShipDate");
				this.OnLastShipDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterType", DbType="NVarChar(250)")]
	public string MeterType
	{
		get
		{
			return this._MeterType;
		}
		set
		{
			if ((this._MeterType != value))
			{
				this.OnMeterTypeChanging(value);
				this.SendPropertyChanging();
				this._MeterType = value;
				this.SendPropertyChanged("MeterType");
				this.OnMeterTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LancetType", DbType="NVarChar(250)")]
	public string LancetType
	{
		get
		{
			return this._LancetType;
		}
		set
		{
			if ((this._LancetType != value))
			{
				this.OnLancetTypeChanging(value);
				this.SendPropertyChanging();
				this._LancetType = value;
				this.SendPropertyChanged("LancetType");
				this.OnLancetTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> DueDate
	{
		get
		{
			return this._DueDate;
		}
		set
		{
			if ((this._DueDate != value))
			{
				this.OnDueDateChanging(value);
				this.SendPropertyChanging();
				this._DueDate = value;
				this.SendPropertyChanged("DueDate");
				this.OnDueDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_PMWF_PatientInformation")]
public partial class AS_Alere_PMWF_PatientInformation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _OrderID;
	
	private string _AddressID;
	
	private string _PatientAddress;
	
	private string _City;
	
	private string _State;
	
	private string _Zip;
	
	private string _Phone;
	
	private string _EMail;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnOrderIDChanging(string value);
    partial void OnOrderIDChanged();
    partial void OnAddressIDChanging(string value);
    partial void OnAddressIDChanged();
    partial void OnPatientAddressChanging(string value);
    partial void OnPatientAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    #endregion
	
	public AS_Alere_PMWF_PatientInformation()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressID", DbType="NVarChar(250)")]
	public string AddressID
	{
		get
		{
			return this._AddressID;
		}
		set
		{
			if ((this._AddressID != value))
			{
				this.OnAddressIDChanging(value);
				this.SendPropertyChanging();
				this._AddressID = value;
				this.SendPropertyChanged("AddressID");
				this.OnAddressIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(250)")]
	public string PatientAddress
	{
		get
		{
			return this._PatientAddress;
		}
		set
		{
			if ((this._PatientAddress != value))
			{
				this.OnPatientAddressChanging(value);
				this.SendPropertyChanging();
				this._PatientAddress = value;
				this.SendPropertyChanged("PatientAddress");
				this.OnPatientAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(250)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(250)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(250)")]
	public string Zip
	{
		get
		{
			return this._Zip;
		}
		set
		{
			if ((this._Zip != value))
			{
				this.OnZipChanging(value);
				this.SendPropertyChanging();
				this._Zip = value;
				this.SendPropertyChanged("Zip");
				this.OnZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(250)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(250)")]
	public string EMail
	{
		get
		{
			return this._EMail;
		}
		set
		{
			if ((this._EMail != value))
			{
				this.OnEMailChanging(value);
				this.SendPropertyChanging();
				this._EMail = value;
				this.SendPropertyChanged("EMail");
				this.OnEMailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlereBasicInformation")]
public partial class AS_WF_VW_PMWF_AlereBasicInformation
{
	
	private string _PatientID;
	
	private string _FirstName;
	
	private string _LastName;
	
	private System.DateTime _DOB;
	
	private string _CustomerClass;
	
	private string _LastShipDate;
	
	private string _MeterType;
	
	private string _LancetType;
	
	public AS_WF_VW_PMWF_AlereBasicInformation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="VarChar(9)")]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="Char(15) NOT NULL", CanBeNull=false)]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this._FirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="Char(25) NOT NULL", CanBeNull=false)]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this._LastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
	public System.DateTime DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerClass", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string CustomerClass
	{
		get
		{
			return this._CustomerClass;
		}
		set
		{
			if ((this._CustomerClass != value))
			{
				this._CustomerClass = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastShipDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string LastShipDate
	{
		get
		{
			return this._LastShipDate;
		}
		set
		{
			if ((this._LastShipDate != value))
			{
				this._LastShipDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterType", DbType="Char(7)")]
	public string MeterType
	{
		get
		{
			return this._MeterType;
		}
		set
		{
			if ((this._MeterType != value))
			{
				this._MeterType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LancetType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string LancetType
	{
		get
		{
			return this._LancetType;
		}
		set
		{
			if ((this._LancetType != value))
			{
				this._LancetType = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlerePatientInformation")]
public partial class AS_WF_VW_PMWF_AlerePatientInformation
{
	
	private string _PatientID;
	
	private string _Phone;
	
	private string _Email;
	
	private string _AddressID;
	
	private string _PatientAddress;
	
	private string _City;
	
	private string _State;
	
	private string _Zip;
	
	public AS_WF_VW_PMWF_AlerePatientInformation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="VarChar(9)")]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(14)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(61) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressID", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
	public string AddressID
	{
		get
		{
			return this._AddressID;
		}
		set
		{
			if ((this._AddressID != value))
			{
				this._AddressID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="Char(31) NOT NULL", CanBeNull=false)]
	public string PatientAddress
	{
		get
		{
			return this._PatientAddress;
		}
		set
		{
			if ((this._PatientAddress != value))
			{
				this._PatientAddress = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="Char(25) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this._State = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="Char(11) NOT NULL", CanBeNull=false)]
	public string Zip
	{
		get
		{
			return this._Zip;
		}
		set
		{
			if ((this._Zip != value))
			{
				this._Zip = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlerePatientLookup")]
public partial class AS_WF_VW_PMWF_AlerePatientLookup
{
	
	private string _PATIENTID;
	
	private string _LASTNAME;
	
	private string _FIRSTNAME;
	
	private System.Nullable<System.DateTime> _DOB;
	
	public AS_WF_VW_PMWF_AlerePatientLookup()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PATIENTID", DbType="Char(15) NOT NULL", CanBeNull=false)]
	public string PATIENTID
	{
		get
		{
			return this._PATIENTID;
		}
		set
		{
			if ((this._PATIENTID != value))
			{
				this._PATIENTID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="Char(25)")]
	public string LASTNAME
	{
		get
		{
			return this._LASTNAME;
		}
		set
		{
			if ((this._LASTNAME != value))
			{
				this._LASTNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="Char(15)")]
	public string FIRSTNAME
	{
		get
		{
			return this._FIRSTNAME;
		}
		set
		{
			if ((this._FIRSTNAME != value))
			{
				this._FIRSTNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_PMWF_Orders")]
public partial class AS_Alere_PMWF_Order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _OrderID;
	
	private string _PatientID;
	
	private string _CreatedBy;
	
	private string _WorkflowState;
	
	private string _NoteColumn;
	
	private string _BasicInfoNoteColumn;
	
	private string _PatientInfoNoteColumn;
	
	private string _BatchID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIDChanging(string value);
    partial void OnOrderIDChanged();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnWorkflowStateChanging(string value);
    partial void OnWorkflowStateChanged();
    partial void OnNoteColumnChanging(string value);
    partial void OnNoteColumnChanged();
    partial void OnBasicInfoNoteColumnChanging(string value);
    partial void OnBasicInfoNoteColumnChanged();
    partial void OnPatientInfoNoteColumnChanging(string value);
    partial void OnPatientInfoNoteColumnChanged();
    partial void OnBatchIDChanging(string value);
    partial void OnBatchIDChanged();
    #endregion
	
	public AS_Alere_PMWF_Order()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(250)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowState", DbType="NVarChar(250)")]
	public string WorkflowState
	{
		get
		{
			return this._WorkflowState;
		}
		set
		{
			if ((this._WorkflowState != value))
			{
				this.OnWorkflowStateChanging(value);
				this.SendPropertyChanging();
				this._WorkflowState = value;
				this.SendPropertyChanged("WorkflowState");
				this.OnWorkflowStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteColumn", DbType="NVarChar(MAX)")]
	public string NoteColumn
	{
		get
		{
			return this._NoteColumn;
		}
		set
		{
			if ((this._NoteColumn != value))
			{
				this.OnNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._NoteColumn = value;
				this.SendPropertyChanged("NoteColumn");
				this.OnNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicInfoNoteColumn", DbType="NVarChar(MAX)")]
	public string BasicInfoNoteColumn
	{
		get
		{
			return this._BasicInfoNoteColumn;
		}
		set
		{
			if ((this._BasicInfoNoteColumn != value))
			{
				this.OnBasicInfoNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._BasicInfoNoteColumn = value;
				this.SendPropertyChanged("BasicInfoNoteColumn");
				this.OnBasicInfoNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientInfoNoteColumn", DbType="NVarChar(MAX)")]
	public string PatientInfoNoteColumn
	{
		get
		{
			return this._PatientInfoNoteColumn;
		}
		set
		{
			if ((this._PatientInfoNoteColumn != value))
			{
				this.OnPatientInfoNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._PatientInfoNoteColumn = value;
				this.SendPropertyChanged("PatientInfoNoteColumn");
				this.OnPatientInfoNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchID", DbType="NVarChar(250)")]
	public string BatchID
	{
		get
		{
			return this._BatchID;
		}
		set
		{
			if ((this._BatchID != value))
			{
				this.OnBatchIDChanging(value);
				this.SendPropertyChanging();
				this._BatchID = value;
				this.SendPropertyChanged("BatchID");
				this.OnBatchIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_PMWF_ItemList")]
public partial class AS_Alere_PMWF_ItemList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ItemSKU;
	
	private string _Description;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemSKUChanging(string value);
    partial void OnItemSKUChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
	
	public AS_Alere_PMWF_ItemList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemSKU", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ItemSKU
	{
		get
		{
			return this._ItemSKU;
		}
		set
		{
			if ((this._ItemSKU != value))
			{
				this.OnItemSKUChanging(value);
				this.SendPropertyChanging();
				this._ItemSKU = value;
				this.SendPropertyChanged("ItemSKU");
				this.OnItemSKUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(250)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
