#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TWO")]
public partial class AlereHomeMonitoringDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAS_Alere_OrderDetail(AS_Alere_OrderDetail instance);
  partial void UpdateAS_Alere_OrderDetail(AS_Alere_OrderDetail instance);
  partial void DeleteAS_Alere_OrderDetail(AS_Alere_OrderDetail instance);
  partial void InsertAS_Alere_Order(AS_Alere_Order instance);
  partial void UpdateAS_Alere_Order(AS_Alere_Order instance);
  partial void DeleteAS_Alere_Order(AS_Alere_Order instance);
  partial void InsertAS_Alere_DoctorInformation(AS_Alere_DoctorInformation instance);
  partial void UpdateAS_Alere_DoctorInformation(AS_Alere_DoctorInformation instance);
  partial void DeleteAS_Alere_DoctorInformation(AS_Alere_DoctorInformation instance);
  partial void InsertAS_Alere_InsuranceInformation(AS_Alere_InsuranceInformation instance);
  partial void UpdateAS_Alere_InsuranceInformation(AS_Alere_InsuranceInformation instance);
  partial void DeleteAS_Alere_InsuranceInformation(AS_Alere_InsuranceInformation instance);
  partial void InsertAS_Alere_PatientInformation(AS_Alere_PatientInformation instance);
  partial void UpdateAS_Alere_PatientInformation(AS_Alere_PatientInformation instance);
  partial void DeleteAS_Alere_PatientInformation(AS_Alere_PatientInformation instance);
  #endregion
	
	public AlereHomeMonitoringDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TWOConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public AlereHomeMonitoringDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlereHomeMonitoringDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlereHomeMonitoringDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AlereHomeMonitoringDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AS_WF_VW_AlereOrderLookup> AS_WF_VW_AlereOrderLookups
	{
		get
		{
			return this.GetTable<AS_WF_VW_AlereOrderLookup>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_AlereDoctorInformation> AS_WF_VW_AlereDoctorInformations
	{
		get
		{
			return this.GetTable<AS_WF_VW_AlereDoctorInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_AlerePatientInformation> AS_WF_VW_AlerePatientInformations
	{
		get
		{
			return this.GetTable<AS_WF_VW_AlerePatientInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_AlereInsuranceInformation> AS_WF_VW_AlereInsuranceInformations
	{
		get
		{
			return this.GetTable<AS_WF_VW_AlereInsuranceInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_AlerePatientLookup> AS_WF_VW_AlerePatientLookups
	{
		get
		{
			return this.GetTable<AS_WF_VW_AlerePatientLookup>();
		}
	}
	
	public System.Data.Linq.Table<AS_WF_VW_AlereBasicInformation> AS_WF_VW_AlereBasicInformations
	{
		get
		{
			return this.GetTable<AS_WF_VW_AlereBasicInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_OrderDetail> AS_Alere_OrderDetails
	{
		get
		{
			return this.GetTable<AS_Alere_OrderDetail>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_Order> AS_Alere_Orders
	{
		get
		{
			return this.GetTable<AS_Alere_Order>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_BasicInformation> AS_Alere_BasicInformations
	{
		get
		{
			return this.GetTable<AS_Alere_BasicInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_DoctorInformation> AS_Alere_DoctorInformations
	{
		get
		{
			return this.GetTable<AS_Alere_DoctorInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_InsuranceInformation> AS_Alere_InsuranceInformations
	{
		get
		{
			return this.GetTable<AS_Alere_InsuranceInformation>();
		}
	}
	
	public System.Data.Linq.Table<AS_Alere_PatientInformation> AS_Alere_PatientInformations
	{
		get
		{
			return this.GetTable<AS_Alere_PatientInformation>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlereOrderLookup")]
public partial class AS_WF_VW_AlereOrderLookup
{
	
	private string _OrderID;
	
	private string _WorkflowState;
	
	private string _PatientID;
	
	private string _FirstName;
	
	private string _LastName;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private System.Nullable<decimal> _TotalAmount;
	
	public AS_WF_VW_AlereOrderLookup()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this._OrderID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowState", DbType="NVarChar(250)")]
	public string WorkflowState
	{
		get
		{
			return this._WorkflowState;
		}
		set
		{
			if ((this._WorkflowState != value))
			{
				this._WorkflowState = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15)")]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(250)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this._FirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(250)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this._LastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> TotalAmount
	{
		get
		{
			return this._TotalAmount;
		}
		set
		{
			if ((this._TotalAmount != value))
			{
				this._TotalAmount = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlereDoctorInformation")]
public partial class AS_WF_VW_AlereDoctorInformation
{
	
	private string _PatientID;
	
	private string _Name;
	
	private string _PhoneNumber;
	
	private string _City;
	
	private string _State;
	
	private string _Zip;
	
	private string _ClinicCode;
	
	private string _Clinic;
	
	public AS_WF_VW_AlereDoctorInformation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Char(9) NOT NULL", CanBeNull=false)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Char(11)")]
	public string PhoneNumber
	{
		get
		{
			return this._PhoneNumber;
		}
		set
		{
			if ((this._PhoneNumber != value))
			{
				this._PhoneNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="Char(25)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(3)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this._State = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="Char(11)")]
	public string Zip
	{
		get
		{
			return this._Zip;
		}
		set
		{
			if ((this._Zip != value))
			{
				this._Zip = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicCode", DbType="Char(7) NOT NULL", CanBeNull=false)]
	public string ClinicCode
	{
		get
		{
			return this._ClinicCode;
		}
		set
		{
			if ((this._ClinicCode != value))
			{
				this._ClinicCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clinic", DbType="VarChar(50)")]
	public string Clinic
	{
		get
		{
			return this._Clinic;
		}
		set
		{
			if ((this._Clinic != value))
			{
				this._Clinic = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlerePatientInformation")]
public partial class AS_WF_VW_AlerePatientInformation
{
	
	private string _PatientID;
	
	private string _Phone;
	
	private string _Email;
	
	private string _AddressID;
	
	private string _PatientAddress;
	
	private string _City;
	
	private string _State;
	
	private string _Zip;
	
	public AS_WF_VW_AlerePatientInformation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Char(9) NOT NULL", CanBeNull=false)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(14)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(61) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressID", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string AddressID
	{
		get
		{
			return this._AddressID;
		}
		set
		{
			if ((this._AddressID != value))
			{
				this._AddressID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="Char(31) NOT NULL", CanBeNull=false)]
	public string PatientAddress
	{
		get
		{
			return this._PatientAddress;
		}
		set
		{
			if ((this._PatientAddress != value))
			{
				this._PatientAddress = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="Char(25) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this._State = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="Char(11) NOT NULL", CanBeNull=false)]
	public string Zip
	{
		get
		{
			return this._Zip;
		}
		set
		{
			if ((this._Zip != value))
			{
				this._Zip = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlereInsuranceInformation")]
public partial class AS_WF_VW_AlereInsuranceInformation
{
	
	private string _PatientID;
	
	private string _PrimaryPlan;
	
	private string _PrimaryPolicyNumber;
	
	private string _PrimaryGroupNumber;
	
	private string _PrimaryClaimPhoneNumber;
	
	private string _PrimaryAddress;
	
	private string _PrimaryCity;
	
	private string _PrimaryState;
	
	private string _PrimaryZip;
	
	private System.Nullable<System.DateTime> _PrimaryEffectivityDate;
	
	private string _SecondaryPlan;
	
	private string _SecondaryPolicyNumber;
	
	private string _SecondaryGroupNumber;
	
	private string _SecondaryClaimPhoneNumber;
	
	private string _SecondaryAddress;
	
	private string _SecondaryCity;
	
	private string _SecondaryState;
	
	private string _SecondaryZip;
	
	private System.Nullable<System.DateTime> _SecondaryEffectivityDate;
	
	public AS_WF_VW_AlereInsuranceInformation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Char(9) NOT NULL", CanBeNull=false)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPlan", DbType="VarChar(30)")]
	public string PrimaryPlan
	{
		get
		{
			return this._PrimaryPlan;
		}
		set
		{
			if ((this._PrimaryPlan != value))
			{
				this._PrimaryPlan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPolicyNumber", DbType="VarChar(19)")]
	public string PrimaryPolicyNumber
	{
		get
		{
			return this._PrimaryPolicyNumber;
		}
		set
		{
			if ((this._PrimaryPolicyNumber != value))
			{
				this._PrimaryPolicyNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryGroupNumber", DbType="VarChar(19)")]
	public string PrimaryGroupNumber
	{
		get
		{
			return this._PrimaryGroupNumber;
		}
		set
		{
			if ((this._PrimaryGroupNumber != value))
			{
				this._PrimaryGroupNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryClaimPhoneNumber", DbType="Char(11)")]
	public string PrimaryClaimPhoneNumber
	{
		get
		{
			return this._PrimaryClaimPhoneNumber;
		}
		set
		{
			if ((this._PrimaryClaimPhoneNumber != value))
			{
				this._PrimaryClaimPhoneNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryAddress", DbType="Char(31)")]
	public string PrimaryAddress
	{
		get
		{
			return this._PrimaryAddress;
		}
		set
		{
			if ((this._PrimaryAddress != value))
			{
				this._PrimaryAddress = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCity", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string PrimaryCity
	{
		get
		{
			return this._PrimaryCity;
		}
		set
		{
			if ((this._PrimaryCity != value))
			{
				this._PrimaryCity = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryState", DbType="Char(3)")]
	public string PrimaryState
	{
		get
		{
			return this._PrimaryState;
		}
		set
		{
			if ((this._PrimaryState != value))
			{
				this._PrimaryState = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryZip", DbType="Char(11)")]
	public string PrimaryZip
	{
		get
		{
			return this._PrimaryZip;
		}
		set
		{
			if ((this._PrimaryZip != value))
			{
				this._PrimaryZip = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryEffectivityDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> PrimaryEffectivityDate
	{
		get
		{
			return this._PrimaryEffectivityDate;
		}
		set
		{
			if ((this._PrimaryEffectivityDate != value))
			{
				this._PrimaryEffectivityDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPlan", DbType="VarChar(30)")]
	public string SecondaryPlan
	{
		get
		{
			return this._SecondaryPlan;
		}
		set
		{
			if ((this._SecondaryPlan != value))
			{
				this._SecondaryPlan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPolicyNumber", DbType="VarChar(19)")]
	public string SecondaryPolicyNumber
	{
		get
		{
			return this._SecondaryPolicyNumber;
		}
		set
		{
			if ((this._SecondaryPolicyNumber != value))
			{
				this._SecondaryPolicyNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryGroupNumber", DbType="VarChar(19)")]
	public string SecondaryGroupNumber
	{
		get
		{
			return this._SecondaryGroupNumber;
		}
		set
		{
			if ((this._SecondaryGroupNumber != value))
			{
				this._SecondaryGroupNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryClaimPhoneNumber", DbType="Char(11)")]
	public string SecondaryClaimPhoneNumber
	{
		get
		{
			return this._SecondaryClaimPhoneNumber;
		}
		set
		{
			if ((this._SecondaryClaimPhoneNumber != value))
			{
				this._SecondaryClaimPhoneNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryAddress", DbType="Char(31)")]
	public string SecondaryAddress
	{
		get
		{
			return this._SecondaryAddress;
		}
		set
		{
			if ((this._SecondaryAddress != value))
			{
				this._SecondaryAddress = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryCity", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string SecondaryCity
	{
		get
		{
			return this._SecondaryCity;
		}
		set
		{
			if ((this._SecondaryCity != value))
			{
				this._SecondaryCity = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryState", DbType="Char(3)")]
	public string SecondaryState
	{
		get
		{
			return this._SecondaryState;
		}
		set
		{
			if ((this._SecondaryState != value))
			{
				this._SecondaryState = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryZip", DbType="Char(11)")]
	public string SecondaryZip
	{
		get
		{
			return this._SecondaryZip;
		}
		set
		{
			if ((this._SecondaryZip != value))
			{
				this._SecondaryZip = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryEffectivityDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> SecondaryEffectivityDate
	{
		get
		{
			return this._SecondaryEffectivityDate;
		}
		set
		{
			if ((this._SecondaryEffectivityDate != value))
			{
				this._SecondaryEffectivityDate = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlerePatientLookup")]
public partial class AS_WF_VW_AlerePatientLookup
{
	
	private string _PATIENTID;
	
	private string _LASTNAME;
	
	private string _FIRSTNAME;
	
	private System.Nullable<System.DateTime> _DOB;
	
	public AS_WF_VW_AlerePatientLookup()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PATIENTID", DbType="Char(15) NOT NULL", CanBeNull=false)]
	public string PATIENTID
	{
		get
		{
			return this._PATIENTID;
		}
		set
		{
			if ((this._PATIENTID != value))
			{
				this._PATIENTID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="Char(25)")]
	public string LASTNAME
	{
		get
		{
			return this._LASTNAME;
		}
		set
		{
			if ((this._LASTNAME != value))
			{
				this._LASTNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="Char(15)")]
	public string FIRSTNAME
	{
		get
		{
			return this._FIRSTNAME;
		}
		set
		{
			if ((this._FIRSTNAME != value))
			{
				this._FIRSTNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_WF_VW_AlereBasicInformation")]
public partial class AS_WF_VW_AlereBasicInformation
{
	
	private string _PatientID;
	
	private string _FirstName;
	
	private string _LastName;
	
	private System.DateTime _DOB;
	
	private string _CustomerClass;
	
	private string _LastShipDate;
	
	private string _MeterType;
	
	private string _LancetType;
	
	public AS_WF_VW_AlereBasicInformation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="VarChar(9)")]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="Char(15) NOT NULL", CanBeNull=false)]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this._FirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="Char(25) NOT NULL", CanBeNull=false)]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this._LastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
	public System.DateTime DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerClass", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string CustomerClass
	{
		get
		{
			return this._CustomerClass;
		}
		set
		{
			if ((this._CustomerClass != value))
			{
				this._CustomerClass = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastShipDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string LastShipDate
	{
		get
		{
			return this._LastShipDate;
		}
		set
		{
			if ((this._LastShipDate != value))
			{
				this._LastShipDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterType", DbType="Char(7)")]
	public string MeterType
	{
		get
		{
			return this._MeterType;
		}
		set
		{
			if ((this._MeterType != value))
			{
				this._MeterType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LancetType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string LancetType
	{
		get
		{
			return this._LancetType;
		}
		set
		{
			if ((this._LancetType != value))
			{
				this._LancetType = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_OrderDetail")]
public partial class AS_Alere_OrderDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _OrderID;
	
	private string _ItemSKU;
	
	private string _Description;
	
	private System.Nullable<decimal> _UnitPrice;
	
	private System.Nullable<int> _Quantity;
	
	private System.Nullable<decimal> _ExtendedPrice;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnOrderIDChanging(string value);
    partial void OnOrderIDChanged();
    partial void OnItemSKUChanging(string value);
    partial void OnItemSKUChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUnitPriceChanging(System.Nullable<decimal> value);
    partial void OnUnitPriceChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    partial void OnExtendedPriceChanging(System.Nullable<decimal> value);
    partial void OnExtendedPriceChanged();
    #endregion
	
	public AS_Alere_OrderDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemSKU", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ItemSKU
	{
		get
		{
			return this._ItemSKU;
		}
		set
		{
			if ((this._ItemSKU != value))
			{
				this.OnItemSKUChanging(value);
				this.SendPropertyChanging();
				this._ItemSKU = value;
				this.SendPropertyChanged("ItemSKU");
				this.OnItemSKUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(250)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> UnitPrice
	{
		get
		{
			return this._UnitPrice;
		}
		set
		{
			if ((this._UnitPrice != value))
			{
				this.OnUnitPriceChanging(value);
				this.SendPropertyChanging();
				this._UnitPrice = value;
				this.SendPropertyChanged("UnitPrice");
				this.OnUnitPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
	public System.Nullable<int> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtendedPrice", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> ExtendedPrice
	{
		get
		{
			return this._ExtendedPrice;
		}
		set
		{
			if ((this._ExtendedPrice != value))
			{
				this.OnExtendedPriceChanging(value);
				this.SendPropertyChanging();
				this._ExtendedPrice = value;
				this.SendPropertyChanged("ExtendedPrice");
				this.OnExtendedPriceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_Orders")]
public partial class AS_Alere_Order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _OrderID;
	
	private System.Nullable<decimal> _TotalAmount;
	
	private string _ShippingMethodID;
	
	private System.Nullable<bool> _SuppliesNotNeeded;
	
	private string _WorkflowState;
	
	private string _CreatedBy;
	
	private System.Nullable<bool> _PatientChanged;
	
	private System.Nullable<bool> _DoctorChanged;
	
	private System.Nullable<bool> _InsuranceChanged;
	
	private string _NoteColumn;
	
	private string _BasicInfoNoteColumn;
	
	private string _DoctorInfoNoteColumn;
	
	private string _InsuranceInfoNoteColumn;
	
	private string _PatientInfoNoteColumn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnOrderIDChanging(string value);
    partial void OnOrderIDChanged();
    partial void OnTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountChanged();
    partial void OnShippingMethodIDChanging(string value);
    partial void OnShippingMethodIDChanged();
    partial void OnSuppliesNotNeededChanging(System.Nullable<bool> value);
    partial void OnSuppliesNotNeededChanged();
    partial void OnWorkflowStateChanging(string value);
    partial void OnWorkflowStateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnPatientChangedChanging(System.Nullable<bool> value);
    partial void OnPatientChangedChanged();
    partial void OnDoctorChangedChanging(System.Nullable<bool> value);
    partial void OnDoctorChangedChanged();
    partial void OnInsuranceChangedChanging(System.Nullable<bool> value);
    partial void OnInsuranceChangedChanged();
    partial void OnNoteColumnChanging(string value);
    partial void OnNoteColumnChanged();
    partial void OnBasicInfoNoteColumnChanging(string value);
    partial void OnBasicInfoNoteColumnChanged();
    partial void OnDoctorInfoNoteColumnChanging(string value);
    partial void OnDoctorInfoNoteColumnChanged();
    partial void OnInsuranceInfoNoteColumnChanging(string value);
    partial void OnInsuranceInfoNoteColumnChanged();
    partial void OnPatientInfoNoteColumnChanging(string value);
    partial void OnPatientInfoNoteColumnChanged();
    #endregion
	
	public AS_Alere_Order()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> TotalAmount
	{
		get
		{
			return this._TotalAmount;
		}
		set
		{
			if ((this._TotalAmount != value))
			{
				this.OnTotalAmountChanging(value);
				this.SendPropertyChanging();
				this._TotalAmount = value;
				this.SendPropertyChanged("TotalAmount");
				this.OnTotalAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingMethodID", DbType="NVarChar(250)")]
	public string ShippingMethodID
	{
		get
		{
			return this._ShippingMethodID;
		}
		set
		{
			if ((this._ShippingMethodID != value))
			{
				this.OnShippingMethodIDChanging(value);
				this.SendPropertyChanging();
				this._ShippingMethodID = value;
				this.SendPropertyChanged("ShippingMethodID");
				this.OnShippingMethodIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuppliesNotNeeded", DbType="Bit")]
	public System.Nullable<bool> SuppliesNotNeeded
	{
		get
		{
			return this._SuppliesNotNeeded;
		}
		set
		{
			if ((this._SuppliesNotNeeded != value))
			{
				this.OnSuppliesNotNeededChanging(value);
				this.SendPropertyChanging();
				this._SuppliesNotNeeded = value;
				this.SendPropertyChanged("SuppliesNotNeeded");
				this.OnSuppliesNotNeededChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkflowState", DbType="NVarChar(250)")]
	public string WorkflowState
	{
		get
		{
			return this._WorkflowState;
		}
		set
		{
			if ((this._WorkflowState != value))
			{
				this.OnWorkflowStateChanging(value);
				this.SendPropertyChanging();
				this._WorkflowState = value;
				this.SendPropertyChanged("WorkflowState");
				this.OnWorkflowStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(250)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientChanged", DbType="Bit")]
	public System.Nullable<bool> PatientChanged
	{
		get
		{
			return this._PatientChanged;
		}
		set
		{
			if ((this._PatientChanged != value))
			{
				this.OnPatientChangedChanging(value);
				this.SendPropertyChanging();
				this._PatientChanged = value;
				this.SendPropertyChanged("PatientChanged");
				this.OnPatientChangedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorChanged", DbType="Bit")]
	public System.Nullable<bool> DoctorChanged
	{
		get
		{
			return this._DoctorChanged;
		}
		set
		{
			if ((this._DoctorChanged != value))
			{
				this.OnDoctorChangedChanging(value);
				this.SendPropertyChanging();
				this._DoctorChanged = value;
				this.SendPropertyChanged("DoctorChanged");
				this.OnDoctorChangedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceChanged", DbType="Bit")]
	public System.Nullable<bool> InsuranceChanged
	{
		get
		{
			return this._InsuranceChanged;
		}
		set
		{
			if ((this._InsuranceChanged != value))
			{
				this.OnInsuranceChangedChanging(value);
				this.SendPropertyChanging();
				this._InsuranceChanged = value;
				this.SendPropertyChanged("InsuranceChanged");
				this.OnInsuranceChangedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteColumn", DbType="NVarChar(MAX)")]
	public string NoteColumn
	{
		get
		{
			return this._NoteColumn;
		}
		set
		{
			if ((this._NoteColumn != value))
			{
				this.OnNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._NoteColumn = value;
				this.SendPropertyChanged("NoteColumn");
				this.OnNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicInfoNoteColumn", DbType="NVarChar(MAX)")]
	public string BasicInfoNoteColumn
	{
		get
		{
			return this._BasicInfoNoteColumn;
		}
		set
		{
			if ((this._BasicInfoNoteColumn != value))
			{
				this.OnBasicInfoNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._BasicInfoNoteColumn = value;
				this.SendPropertyChanged("BasicInfoNoteColumn");
				this.OnBasicInfoNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorInfoNoteColumn", DbType="NVarChar(MAX)")]
	public string DoctorInfoNoteColumn
	{
		get
		{
			return this._DoctorInfoNoteColumn;
		}
		set
		{
			if ((this._DoctorInfoNoteColumn != value))
			{
				this.OnDoctorInfoNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._DoctorInfoNoteColumn = value;
				this.SendPropertyChanged("DoctorInfoNoteColumn");
				this.OnDoctorInfoNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceInfoNoteColumn", DbType="NVarChar(MAX)")]
	public string InsuranceInfoNoteColumn
	{
		get
		{
			return this._InsuranceInfoNoteColumn;
		}
		set
		{
			if ((this._InsuranceInfoNoteColumn != value))
			{
				this.OnInsuranceInfoNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._InsuranceInfoNoteColumn = value;
				this.SendPropertyChanged("InsuranceInfoNoteColumn");
				this.OnInsuranceInfoNoteColumnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientInfoNoteColumn", DbType="NVarChar(MAX)")]
	public string PatientInfoNoteColumn
	{
		get
		{
			return this._PatientInfoNoteColumn;
		}
		set
		{
			if ((this._PatientInfoNoteColumn != value))
			{
				this.OnPatientInfoNoteColumnChanging(value);
				this.SendPropertyChanging();
				this._PatientInfoNoteColumn = value;
				this.SendPropertyChanged("PatientInfoNoteColumn");
				this.OnPatientInfoNoteColumnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_BasicInformation")]
public partial class AS_Alere_BasicInformation
{
	
	private string _PatientID;
	
	private string _FirstName;
	
	private string _LastName;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _CustomerClass;
	
	private System.Nullable<System.DateTime> _LastShipDate;
	
	private string _MeterType;
	
	private string _LancetType;
	
	private System.Nullable<System.DateTime> _DueDate;
	
	public AS_Alere_BasicInformation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(250)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this._FirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(250)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this._LastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerClass", DbType="NVarChar(50)")]
	public string CustomerClass
	{
		get
		{
			return this._CustomerClass;
		}
		set
		{
			if ((this._CustomerClass != value))
			{
				this._CustomerClass = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastShipDate", DbType="Date")]
	public System.Nullable<System.DateTime> LastShipDate
	{
		get
		{
			return this._LastShipDate;
		}
		set
		{
			if ((this._LastShipDate != value))
			{
				this._LastShipDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterType", DbType="NVarChar(250)")]
	public string MeterType
	{
		get
		{
			return this._MeterType;
		}
		set
		{
			if ((this._MeterType != value))
			{
				this._MeterType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LancetType", DbType="NVarChar(250)")]
	public string LancetType
	{
		get
		{
			return this._LancetType;
		}
		set
		{
			if ((this._LancetType != value))
			{
				this._LancetType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> DueDate
	{
		get
		{
			return this._DueDate;
		}
		set
		{
			if ((this._DueDate != value))
			{
				this._DueDate = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_DoctorInformation")]
public partial class AS_Alere_DoctorInformation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _DoctorName;
	
	private string _PhoneNumber;
	
	private string _City;
	
	private string _State;
	
	private string _Zip;
	
	private string _Clinic;
	
	private string _ClinicCode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnDoctorNameChanging(string value);
    partial void OnDoctorNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnClinicChanging(string value);
    partial void OnClinicChanged();
    partial void OnClinicCodeChanging(string value);
    partial void OnClinicCodeChanged();
    #endregion
	
	public AS_Alere_DoctorInformation()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorName", DbType="NVarChar(250)")]
	public string DoctorName
	{
		get
		{
			return this._DoctorName;
		}
		set
		{
			if ((this._DoctorName != value))
			{
				this.OnDoctorNameChanging(value);
				this.SendPropertyChanging();
				this._DoctorName = value;
				this.SendPropertyChanged("DoctorName");
				this.OnDoctorNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(250)")]
	public string PhoneNumber
	{
		get
		{
			return this._PhoneNumber;
		}
		set
		{
			if ((this._PhoneNumber != value))
			{
				this.OnPhoneNumberChanging(value);
				this.SendPropertyChanging();
				this._PhoneNumber = value;
				this.SendPropertyChanged("PhoneNumber");
				this.OnPhoneNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(250)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(250)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(250)")]
	public string Zip
	{
		get
		{
			return this._Zip;
		}
		set
		{
			if ((this._Zip != value))
			{
				this.OnZipChanging(value);
				this.SendPropertyChanging();
				this._Zip = value;
				this.SendPropertyChanged("Zip");
				this.OnZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clinic", DbType="NVarChar(250)")]
	public string Clinic
	{
		get
		{
			return this._Clinic;
		}
		set
		{
			if ((this._Clinic != value))
			{
				this.OnClinicChanging(value);
				this.SendPropertyChanging();
				this._Clinic = value;
				this.SendPropertyChanged("Clinic");
				this.OnClinicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicCode", DbType="NVarChar(250)")]
	public string ClinicCode
	{
		get
		{
			return this._ClinicCode;
		}
		set
		{
			if ((this._ClinicCode != value))
			{
				this.OnClinicCodeChanging(value);
				this.SendPropertyChanging();
				this._ClinicCode = value;
				this.SendPropertyChanged("ClinicCode");
				this.OnClinicCodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_InsuranceInformation")]
public partial class AS_Alere_InsuranceInformation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _PrimaryPlan;
	
	private string _PrimaryPolicyNumber;
	
	private string _PrimaryGroupNumber;
	
	private string _PrimaryClaimPhoneNumber;
	
	private string _PrimaryAddress;
	
	private string _PrimaryCity;
	
	private string _PrimaryState;
	
	private string _PrimaryZip;
	
	private System.Nullable<System.DateTime> _PrimaryEffectivityDate;
	
	private string _SecondaryPlan;
	
	private string _SecondaryPolicyNumber;
	
	private string _SecondaryGroupNumber;
	
	private string _SecondaryClaimPhoneNumber;
	
	private string _SecondaryAddress;
	
	private string _SecondaryCity;
	
	private string _SecondaryState;
	
	private string _SecondaryZip;
	
	private System.Nullable<System.DateTime> _SecondaryEffectivityDate;
	
	private System.Nullable<bool> _SupplyOrder;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnPrimaryPlanChanging(string value);
    partial void OnPrimaryPlanChanged();
    partial void OnPrimaryPolicyNumberChanging(string value);
    partial void OnPrimaryPolicyNumberChanged();
    partial void OnPrimaryGroupNumberChanging(string value);
    partial void OnPrimaryGroupNumberChanged();
    partial void OnPrimaryClaimPhoneNumberChanging(string value);
    partial void OnPrimaryClaimPhoneNumberChanged();
    partial void OnPrimaryAddressChanging(string value);
    partial void OnPrimaryAddressChanged();
    partial void OnPrimaryCityChanging(string value);
    partial void OnPrimaryCityChanged();
    partial void OnPrimaryStateChanging(string value);
    partial void OnPrimaryStateChanged();
    partial void OnPrimaryZipChanging(string value);
    partial void OnPrimaryZipChanged();
    partial void OnPrimaryEffectivityDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPrimaryEffectivityDateChanged();
    partial void OnSecondaryPlanChanging(string value);
    partial void OnSecondaryPlanChanged();
    partial void OnSecondaryPolicyNumberChanging(string value);
    partial void OnSecondaryPolicyNumberChanged();
    partial void OnSecondaryGroupNumberChanging(string value);
    partial void OnSecondaryGroupNumberChanged();
    partial void OnSecondaryClaimPhoneNumberChanging(string value);
    partial void OnSecondaryClaimPhoneNumberChanged();
    partial void OnSecondaryAddressChanging(string value);
    partial void OnSecondaryAddressChanged();
    partial void OnSecondaryCityChanging(string value);
    partial void OnSecondaryCityChanged();
    partial void OnSecondaryStateChanging(string value);
    partial void OnSecondaryStateChanged();
    partial void OnSecondaryZipChanging(string value);
    partial void OnSecondaryZipChanged();
    partial void OnSecondaryEffectivityDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSecondaryEffectivityDateChanged();
    partial void OnSupplyOrderChanging(System.Nullable<bool> value);
    partial void OnSupplyOrderChanged();
    #endregion
	
	public AS_Alere_InsuranceInformation()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPlan", DbType="NVarChar(250)")]
	public string PrimaryPlan
	{
		get
		{
			return this._PrimaryPlan;
		}
		set
		{
			if ((this._PrimaryPlan != value))
			{
				this.OnPrimaryPlanChanging(value);
				this.SendPropertyChanging();
				this._PrimaryPlan = value;
				this.SendPropertyChanged("PrimaryPlan");
				this.OnPrimaryPlanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPolicyNumber", DbType="NVarChar(250)")]
	public string PrimaryPolicyNumber
	{
		get
		{
			return this._PrimaryPolicyNumber;
		}
		set
		{
			if ((this._PrimaryPolicyNumber != value))
			{
				this.OnPrimaryPolicyNumberChanging(value);
				this.SendPropertyChanging();
				this._PrimaryPolicyNumber = value;
				this.SendPropertyChanged("PrimaryPolicyNumber");
				this.OnPrimaryPolicyNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryGroupNumber", DbType="NVarChar(250)")]
	public string PrimaryGroupNumber
	{
		get
		{
			return this._PrimaryGroupNumber;
		}
		set
		{
			if ((this._PrimaryGroupNumber != value))
			{
				this.OnPrimaryGroupNumberChanging(value);
				this.SendPropertyChanging();
				this._PrimaryGroupNumber = value;
				this.SendPropertyChanged("PrimaryGroupNumber");
				this.OnPrimaryGroupNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryClaimPhoneNumber", DbType="NVarChar(250)")]
	public string PrimaryClaimPhoneNumber
	{
		get
		{
			return this._PrimaryClaimPhoneNumber;
		}
		set
		{
			if ((this._PrimaryClaimPhoneNumber != value))
			{
				this.OnPrimaryClaimPhoneNumberChanging(value);
				this.SendPropertyChanging();
				this._PrimaryClaimPhoneNumber = value;
				this.SendPropertyChanged("PrimaryClaimPhoneNumber");
				this.OnPrimaryClaimPhoneNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryAddress", DbType="NVarChar(250)")]
	public string PrimaryAddress
	{
		get
		{
			return this._PrimaryAddress;
		}
		set
		{
			if ((this._PrimaryAddress != value))
			{
				this.OnPrimaryAddressChanging(value);
				this.SendPropertyChanging();
				this._PrimaryAddress = value;
				this.SendPropertyChanged("PrimaryAddress");
				this.OnPrimaryAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCity", DbType="NVarChar(250)")]
	public string PrimaryCity
	{
		get
		{
			return this._PrimaryCity;
		}
		set
		{
			if ((this._PrimaryCity != value))
			{
				this.OnPrimaryCityChanging(value);
				this.SendPropertyChanging();
				this._PrimaryCity = value;
				this.SendPropertyChanged("PrimaryCity");
				this.OnPrimaryCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryState", DbType="NVarChar(250)")]
	public string PrimaryState
	{
		get
		{
			return this._PrimaryState;
		}
		set
		{
			if ((this._PrimaryState != value))
			{
				this.OnPrimaryStateChanging(value);
				this.SendPropertyChanging();
				this._PrimaryState = value;
				this.SendPropertyChanged("PrimaryState");
				this.OnPrimaryStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryZip", DbType="NVarChar(250)")]
	public string PrimaryZip
	{
		get
		{
			return this._PrimaryZip;
		}
		set
		{
			if ((this._PrimaryZip != value))
			{
				this.OnPrimaryZipChanging(value);
				this.SendPropertyChanging();
				this._PrimaryZip = value;
				this.SendPropertyChanged("PrimaryZip");
				this.OnPrimaryZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryEffectivityDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> PrimaryEffectivityDate
	{
		get
		{
			return this._PrimaryEffectivityDate;
		}
		set
		{
			if ((this._PrimaryEffectivityDate != value))
			{
				this.OnPrimaryEffectivityDateChanging(value);
				this.SendPropertyChanging();
				this._PrimaryEffectivityDate = value;
				this.SendPropertyChanged("PrimaryEffectivityDate");
				this.OnPrimaryEffectivityDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPlan", DbType="NVarChar(250)")]
	public string SecondaryPlan
	{
		get
		{
			return this._SecondaryPlan;
		}
		set
		{
			if ((this._SecondaryPlan != value))
			{
				this.OnSecondaryPlanChanging(value);
				this.SendPropertyChanging();
				this._SecondaryPlan = value;
				this.SendPropertyChanged("SecondaryPlan");
				this.OnSecondaryPlanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryPolicyNumber", DbType="NVarChar(250)")]
	public string SecondaryPolicyNumber
	{
		get
		{
			return this._SecondaryPolicyNumber;
		}
		set
		{
			if ((this._SecondaryPolicyNumber != value))
			{
				this.OnSecondaryPolicyNumberChanging(value);
				this.SendPropertyChanging();
				this._SecondaryPolicyNumber = value;
				this.SendPropertyChanged("SecondaryPolicyNumber");
				this.OnSecondaryPolicyNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryGroupNumber", DbType="NVarChar(250)")]
	public string SecondaryGroupNumber
	{
		get
		{
			return this._SecondaryGroupNumber;
		}
		set
		{
			if ((this._SecondaryGroupNumber != value))
			{
				this.OnSecondaryGroupNumberChanging(value);
				this.SendPropertyChanging();
				this._SecondaryGroupNumber = value;
				this.SendPropertyChanged("SecondaryGroupNumber");
				this.OnSecondaryGroupNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryClaimPhoneNumber", DbType="NVarChar(250)")]
	public string SecondaryClaimPhoneNumber
	{
		get
		{
			return this._SecondaryClaimPhoneNumber;
		}
		set
		{
			if ((this._SecondaryClaimPhoneNumber != value))
			{
				this.OnSecondaryClaimPhoneNumberChanging(value);
				this.SendPropertyChanging();
				this._SecondaryClaimPhoneNumber = value;
				this.SendPropertyChanged("SecondaryClaimPhoneNumber");
				this.OnSecondaryClaimPhoneNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryAddress", DbType="NVarChar(250)")]
	public string SecondaryAddress
	{
		get
		{
			return this._SecondaryAddress;
		}
		set
		{
			if ((this._SecondaryAddress != value))
			{
				this.OnSecondaryAddressChanging(value);
				this.SendPropertyChanging();
				this._SecondaryAddress = value;
				this.SendPropertyChanged("SecondaryAddress");
				this.OnSecondaryAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryCity", DbType="NVarChar(250)")]
	public string SecondaryCity
	{
		get
		{
			return this._SecondaryCity;
		}
		set
		{
			if ((this._SecondaryCity != value))
			{
				this.OnSecondaryCityChanging(value);
				this.SendPropertyChanging();
				this._SecondaryCity = value;
				this.SendPropertyChanged("SecondaryCity");
				this.OnSecondaryCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryState", DbType="NVarChar(250)")]
	public string SecondaryState
	{
		get
		{
			return this._SecondaryState;
		}
		set
		{
			if ((this._SecondaryState != value))
			{
				this.OnSecondaryStateChanging(value);
				this.SendPropertyChanging();
				this._SecondaryState = value;
				this.SendPropertyChanged("SecondaryState");
				this.OnSecondaryStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryZip", DbType="NVarChar(250)")]
	public string SecondaryZip
	{
		get
		{
			return this._SecondaryZip;
		}
		set
		{
			if ((this._SecondaryZip != value))
			{
				this.OnSecondaryZipChanging(value);
				this.SendPropertyChanging();
				this._SecondaryZip = value;
				this.SendPropertyChanged("SecondaryZip");
				this.OnSecondaryZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryEffectivityDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> SecondaryEffectivityDate
	{
		get
		{
			return this._SecondaryEffectivityDate;
		}
		set
		{
			if ((this._SecondaryEffectivityDate != value))
			{
				this.OnSecondaryEffectivityDateChanging(value);
				this.SendPropertyChanging();
				this._SecondaryEffectivityDate = value;
				this.SendPropertyChanged("SecondaryEffectivityDate");
				this.OnSecondaryEffectivityDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyOrder", DbType="Bit")]
	public System.Nullable<bool> SupplyOrder
	{
		get
		{
			return this._SupplyOrder;
		}
		set
		{
			if ((this._SupplyOrder != value))
			{
				this.OnSupplyOrderChanging(value);
				this.SendPropertyChanging();
				this._SupplyOrder = value;
				this.SendPropertyChanged("SupplyOrder");
				this.OnSupplyOrderChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AS_Alere_PatientInformation")]
public partial class AS_Alere_PatientInformation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _PatientID;
	
	private string _AddressID;
	
	private string _PatientAddress;
	
	private string _City;
	
	private string _State;
	
	private string _Zip;
	
	private string _Phone;
	
	private string _EMail;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatientIDChanging(string value);
    partial void OnPatientIDChanged();
    partial void OnAddressIDChanging(string value);
    partial void OnAddressIDChanged();
    partial void OnPatientAddressChanging(string value);
    partial void OnPatientAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    #endregion
	
	public AS_Alere_PatientInformation()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressID", DbType="NVarChar(250)")]
	public string AddressID
	{
		get
		{
			return this._AddressID;
		}
		set
		{
			if ((this._AddressID != value))
			{
				this.OnAddressIDChanging(value);
				this.SendPropertyChanging();
				this._AddressID = value;
				this.SendPropertyChanged("AddressID");
				this.OnAddressIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(250)")]
	public string PatientAddress
	{
		get
		{
			return this._PatientAddress;
		}
		set
		{
			if ((this._PatientAddress != value))
			{
				this.OnPatientAddressChanging(value);
				this.SendPropertyChanging();
				this._PatientAddress = value;
				this.SendPropertyChanged("PatientAddress");
				this.OnPatientAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(250)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(250)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(250)")]
	public string Zip
	{
		get
		{
			return this._Zip;
		}
		set
		{
			if ((this._Zip != value))
			{
				this.OnZipChanging(value);
				this.SendPropertyChanging();
				this._Zip = value;
				this.SendPropertyChanged("Zip");
				this.OnZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(250)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(250)")]
	public string EMail
	{
		get
		{
			return this._EMail;
		}
		set
		{
			if ((this._EMail != value))
			{
				this.OnEMailChanging(value);
				this.SendPropertyChanging();
				this._EMail = value;
				this.SendPropertyChanged("EMail");
				this.OnEMailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
