<?xml version="1.0" encoding="utf-8"?><Database Name="TWO" Class="CompanyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=RIC-ASUS\ALBA;Initial Catalog=TWO;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TWOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RM00102" Member="RM00102s">
    <Type Name="RM00102">
      <Column Name="CUSTNMBR" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADRSCODE" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SLPRSNID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="UPSZONE" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="SHIPMTHD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TAXSCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CNTCPRSN" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS1" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS2" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS3" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="COUNTRY" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="Char(35) NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="Char(29) NOT NULL" CanBeNull="false" />
      <Column Name="ZIP" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE1" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE2" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE3" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="FAX" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="MODIFDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATDDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GPSFOINTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONSOURCE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="CCode" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="DECLID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="LOCNCODE" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="SALSTERR" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="USERDEF1" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="USERDEF2" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="RM00101_RM00102" Member="RM00101" ThisKey="CUSTNMBR" OtherKey="CUSTNMBR" Type="RM00101" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RM00101" Member="RM00101s">
    <Type Name="RM00101">
      <Column Name="CUSTNMBR" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CUSTNAME" Type="System.String" DbType="Char(65) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTCLAS" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CPRCSTNM" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CNTCPRSN" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="STMTNAME" Type="System.String" DbType="Char(65) NOT NULL" CanBeNull="false" />
      <Column Name="SHRTNAME" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="ADRSCODE" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="UPSZONE" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="SHIPMTHD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TAXSCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS1" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS2" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS3" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="COUNTRY" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="Char(35) NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="Char(29) NOT NULL" CanBeNull="false" />
      <Column Name="ZIP" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE1" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE2" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE3" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="FAX" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PRBTADCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="PRSTADCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="STADDRCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="SLPRSNID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CHEKBKID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="PYMTRMID" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTPER" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTPAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CURNCYID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="RATETPID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTDISC" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PRCLEVEL" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="MINPYTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MINPYDLR" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="MINPYPCT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FNCHATYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FNCHPCNT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FINCHDLR" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="MXWOFTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MXWROFAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="COMMENT1" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="COMMENT2" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="USERDEF1" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="USERDEF2" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="TAXEXMT1" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="TAXEXMT2" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="TXRGNNUM" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="BALNCTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="STMTCYCL" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BANKNAME" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="BNKBRNCH" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="SALSTERR" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="DEFCACTY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RMCSHACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMARACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMSLSACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMIVACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMCOSACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMTAKACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMAVACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMFCGACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMWRACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMSORACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FRSTINDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INACTIVE" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="HOLD" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CRCARDID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CRCRDNUM" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="CCRDXPDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KPDSTHST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="KPCALHST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="KPERHIST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="KPTRXHST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NOTEINDX" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CREATDDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Revalue_Customer" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Post_Results_To" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FINCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="GOVCRPID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="GOVINDID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="DISGRPER" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DUEGRPER" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DOCFMTID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="Send_Email_Statements" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="USERLANG" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="GPSFOINTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONSOURCE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="ORDERFULFILLDEFAULT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CUSTPRIORITY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CCode" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="DECLID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="RMOvrpymtWrtoffAcctIdx" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SHIPCOMPLETE" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CBVAT" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INCLUDEINDP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="RM00101_RM00102" Member="RM00102s" ThisKey="CUSTNMBR" OtherKey="CUSTNMBR" Type="RM00102" />
    </Type>
  </Table>
  <Table Name="dbo.SOP10100" Member="SOP10100s">
    <Type Name="SOP10100">
      <Column Name="SOPTYPE" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOPNUMBE" Type="System.String" DbType="Char(21) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ORIGTYPE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ORIGNUMB" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="DOCID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="DOCDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GLPOSTDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="QUOTEDAT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="QUOEXPDA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ORDRDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INVODATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BACKDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RETUDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReqShipDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FUFILDAT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ACTLSHIP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DISCDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DUEDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="REPTING" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TRXFREQU" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TIMEREPD" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TIMETREP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DYSTINCR" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DTLSTREP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DSTBTCH1" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="DSTBTCH2" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="USDOCID1" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="USDOCID2" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="DISCFRGT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDAVFRT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCMISC" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDAVMSC" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISAVAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDAVAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISCRTND" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDISRTD" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISTKNAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDISTKN" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DSCPCTAM" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DSCDLRAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDDLRAT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DISAVTKN" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDATKN" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="PYMTRMID" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PRCLEVEL" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="LOCNCODE" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="BCHSOURC" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="BACHNUMB" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTNMBR" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTNAME" Type="System.String" DbType="Char(65) NOT NULL" CanBeNull="false" />
      <Column Name="CSTPONBR" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PROSPECT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MSTRNUMB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PCKSLPNO" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PICTICNU" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="MRKDNAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORMRKDAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="PRBTADCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="PRSTADCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CNTCPRSN" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ShipToName" Type="System.String" DbType="Char(65) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS1" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS2" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS3" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="Char(35) NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="Char(29) NOT NULL" CanBeNull="false" />
      <Column Name="ZIPCODE" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="CCode" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="COUNTRY" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="PHNUMBR1" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHNUMBR2" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE3" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="FAXNUMBR" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="COMAPPTO" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="COMMAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="OCOMMAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CMMSLAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORCOSAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="NCOMAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORNCMAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="SHIPMTHD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TRDISAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORTDISAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="TRDISPCT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SUBTOTAL" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORSUBTOT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="REMSUBTO" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="OREMSUBT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="EXTDCOST" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="OREXTCST" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="FRTAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORFRTAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="MISCAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORMISCAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="TXENGCLD" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TAXEXMT1" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="TAXEXMT2" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="TXRGNNUM" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="TAXSCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TXSCHSRC" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BSIVCTTL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FRTSCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="FRTTXAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORFRTTAX" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="FRGTTXBL" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MSCSCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="MSCTXAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORMSCTAX" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="MISCTXBL" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BKTFRTAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORBKTFRT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="BKTMSCAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORBKTMSC" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="BCKTXAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="OBTAXAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="TXBTXAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="OTAXTAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="TAXAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORTAXAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ECTRX" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DOCAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDOCAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="PYMTRCVD" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORPMTRVD" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="DEPRECVD" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORDEPRVD" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CODAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORCODAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ACCTAMNT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="ORACTAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="SALSTERR" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="SLPRSNID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="UPSZONE" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="TIMESPRT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PSTGSTUS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VOIDSTTS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ALLOCABY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="NOTEINDX" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CURNCYID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CURRNIDX" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RATETPID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="EXGTBLID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="XCHGRATE" Type="System.Decimal" DbType="Decimal(19,7) NOT NULL" CanBeNull="false" />
      <Column Name="DENXRATE" Type="System.Decimal" DbType="Decimal(19,7) NOT NULL" CanBeNull="false" />
      <Column Name="EXCHDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TIME1" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RTCLCMTD" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MCTRXSTT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TRXSORCE" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Column Name="SOPHDRE1" Type="System.Data.Linq.Binary" DbType="Binary(4) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SOPHDRE2" Type="System.Data.Linq.Binary" DbType="Binary(4) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SOPLNERR" Type="System.Data.Linq.Binary" DbType="Binary(4) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SOPHDRFL" Type="System.Data.Linq.Binary" DbType="Binary(4) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SOPMCERR" Type="System.Data.Linq.Binary" DbType="Binary(4) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="COMMNTID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="REFRENCE" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="POSTEDDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PTDUSRID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="USER2ENT" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CREATDDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Tax_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="APLYWITH" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="WITHHAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="SHPPGDOC" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CORRCTN" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SIMPLIFD" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CORRNXST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DOCNCORR" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="SEQNCORR" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SALEDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SOPHDRE3" Type="System.Data.Linq.Binary" DbType="Binary(4) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EXCEPTIONALDEMAND" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Flags" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BackoutTradeDisc" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="OrigBackoutTradeDisc" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="GPSFOINTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONSOURCE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="SOPSTATUS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SHIPCOMPLETE" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DIRECTDEBIT" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="WorkflowApprStatCreditLm" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="WorkflowPriorityCreditLm" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="WorkflowApprStatusQuote" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="WorkflowPriorityQuote" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>